WGBH-MLA/AAPB2

- config/vocab-maps/asset-type-map.txt
- scripts/ci/ci.rb
- scripts/cleaner.rb
> Regex vocab map

- scripts/ci/ci.rb
- spec/scripts/ci_spec.rb
> Ci strangeness

- app/controllers/catalog_controller.rb
- app/models/pb_core.rb
- app/views/catalog/_index_header_default.html.erb
- app/views/catalog/show.erb
- jetty/solr/blacklight-core/conf/schema.xml
- spec/features/catalog_spec.rb
- spec/models/pb_core_spec.rb
fixes #29 , fixes #26 , fixes #28 , fixes #27
> Facets working

- app/controllers/catalog_controller.rb
- app/models/pb_core.rb
- jetty/solr/blacklight-core/conf/schema.xml
- jetty/solr/blacklight-core/conf/solrconfig.xml
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/models/pb_core_spec.rb
> Constrained search 56

- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
> header and footer

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/features/catalog_spec.rb
- spec/models/pb_core_spec.rb
> All IDs, labelled.

- config/vocab-maps/description-type-map.yml
- scripts/cleaner.rb
- spec/fixtures/pbcore/dirty-yes-fix-no-relation-type.xml
> Order descriptions appropriately.

- app/views/organizations/show.html.erb
- spec/features/organizations_spec.rb
> Check for organization links.

- Gemfile
- Gemfile.lock
- app/views/home/_blog.html.erb
@Hammicakes : you can now get a snippet of the blog on the homepage:
```
<%= render partial: 'home/blog'  %>
```
(Going to leave the issue open until it is actually committed to the homepage, wrapped with a cache, and tested.)
> Blog on home

- scripts/download_clean_ingest.rb
- scripts/lib/downloader.rb
fix #186 and fix #184, hopefully?
> Script tweaks

- scripts/lib/cleaner.rb
- spec/fixtures/pbcore/dirty-yes-fix-bad-relation-and-language.xml
> Strip bad dates.

- app/views/catalog/index.html.erb
> Search banner

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/catalog_spec.rb
> Redirect blank catalog searches

- app/views/override/about-the-american-archive.html.erb
replaces mission and vision statements (to be moved) with Alan’s
prospectus
> updates about page text

- app/models/organization.rb
- app/models/pb_core.rb
- scripts/download_clean_ingest.rb
- spec/features/catalog_spec.rb
- spec/models/pb_core_spec.rb
> state abbrevs in org facet.

- config/organizations.yml
makes organization.yml completely up to date with info I've received from stations/contributing organizations.
> add-more-org-info

- scripts/download_clean_ingest.rb
- scripts/lib/downloader.rb
- spec/scripts/downloader_spec.rb
Maybe needs refactoring at some point, but this works.
> Download by ID.

- app/controllers/robots_controller.rb
- config/initializers/mime_types.rb
- config/routes.rb
- public/robots.txt
- spec/features/robots_spec.rb
> robots.txt

- scripts/lib/cleaner.rb
> Exclude future dates

- config/organizations.yml
updated louisiana public broadcasting's url
added filename for wisconsin public televison's logo
> edited org info

- app/views/home/_blog.html.erb
> Catch and log all WP API errors.

- spec/support/code_style_spec.rb
> There was not enough info to tell why it was not running on travis.

- app/views/catalog/_player.html.erb
@afred : please review (and redeploy, if you feel like it, or that can wait.)
> The video and audio elements were essentially identical

- spec/support/validation_helper.rb
- spec/support/validation_helper_spec.rb
done, hopefully. should not have gotten sucked into this.
> XML cleaning for tests. 

- app/views/catalog/_player.html.erb
@caseyedavis12 : This disables the context menu for me on Chrome and FF.
@afred : please review.
> This works on FF and Chrome for me.

- app/assets/stylesheets/application.css
Fixes #385.
@afred: please review.
> Horizontally center player.

- app/assets/stylesheets/homepage.css
- app/views/home/show.html.erb
@caseyedavis12 :
- Does it need a new background image?
- Does it belong at the bottom?
- Does it need a title?
- Should the video on "about" be removed?
> Fixes #411, maybe

- config/vocab-maps/asset-type-map.yml
with new term added to asset type controlled vocab.
> updates asset type vocab map

- scripts/lib/cleaner.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/fixtures/pbcore/clean-bad-title-type.xml
- spec/fixtures/pbcore/clean-no-instantiation-identifier-location-mediaType.xml
- spec/fixtures/pbcore/dirty-yes-fix-bad-relation-and-language.xml
- spec/models/pb_core_spec.rb
- Do we have examples of actual records that need this kind of fix?
- This is applied only to titles which are all lower case... maybe that's not right?
- Capitalization logic itself is questionable.
- Do we have examples where call letter special casing is necessary? How do we distinguish "WILL" from "will"?
> Title casing on ingest.

- app/controllers/errors_controller.rb
- app/views/errors/404.erb
- app/views/errors/500.erb
- config/application.rb
- config/routes.rb
Would fix #161. Not super-confident that this is the right approach.
> Custom 404

- app/views/organizations/show.html.erb
- spec/support/validation_helper.rb
> Html safe in orgs

- app/assets/stylesheets/homepage.css
- app/views/home/show.html.erb
- app/views/override/about-the-american-archive.md
(Chose Eleanor Roosevelt for a banner replacement, but @sroosa can change that.)
> homepage tweaks as requested. 

- app/views/catalog/show.erb
Full reindex with vocab-map in place helpful but not essential
> Fix #393. 

- app/views/catalog/_index_gallery_default.html.erb
- app/views/catalog/_index_list_default.html.erb
(Looked, and passing a block to the BL helper is not an option.)
> Wrap thumbnails with links. fix #394.

- app/views/home/_blog.html.erb
> html_safe to prevent double encoding

- lib/html_scrubber.rb
- spec/lib/html_scrubber_spec.rb
Not yet in use, but I want feedback before going forward with a fix for #439.
> Uncruft html 439

- spec/features/catalog_spec.rb
@afred: Please review. Once this is merged, I'll need to pull it into the two branches which are failing.
> Special test of relevance sort. Fix #467.

- app/controllers/media_controller.rb
I would like this to be tested, but it uses Ci... mock?
@foo4thought : please review.
> Turn off referer check. Fix #459.

- app/models/exhibit.rb
- app/views/catalog/_index_gallery_default.html.erb
- app/views/catalog/_search_header.html.erb
- config/exhibits.yml
- spec/features/catalog_spec.rb
> Exhibit tweaks 432 433

- app/models/pb_core.rb
- spec/fixtures/pbcore/clean-MOCK.xml
> Use the html scrubber on view. fix #439, for now.

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/models/pb_core_spec.rb
Explicit duration accessor instead of going through instantiations.
> Fix #493. 

- scripts/lib/pb_core_ingester.rb
Fix #502. Root problem is not symlink following, it is that we were looking at the wrong path.
@afred: Maybe get this in before we try another ingest?
> We are just symlinking the index subdirectory, not the parent.

- app/views/catalog/_index_list_default.html.erb
- spec/features/catalog_spec.rb
> Titles in search results

- app/views/override/about-the-american-archive/acknowledgments.md
- app/views/override/about-the-american-archive/history/page3.md
- app/views/override/help/using-the-ams.md
- app/views/override/resources.md
- app/views/override/search.md
- app/views/override/social-media.md
This quiets a once-a-week test, bu otherwise is not too useful. I'm ambivalent about this.
> Replace links that are redirects.

- app/models/exhibit.rb
- app/views/exhibits/template.erb
- spec/fixtures/exhibits-broken/extra-cruft/extra-cruft.md
- spec/fixtures/exhibits-broken/misspelled-h2/misspelled-h2.md
- spec/fixtures/exhibits/parent/child/grandchild.md
- spec/fixtures/exhibits/parent/child/grandchild/greatgrandchild1.md
- spec/fixtures/exhibits/parent/child/grandchild/greatgrandchild2.md
- spec/models/exhibit_spec.rb
@afred: Better testing, and the sidebar stuff we had discussed.
> More exhibit stuff

- app/controllers/captions_controller.rb
- app/models/pb_core.rb
- app/views/catalog/_player.html.erb
- config/routes.rb
- jetty/solr/blacklight-core/conf/schema.xml
- spec/models/pb_core_spec.rb
How exactly captions will work may change, but I think defining the interface at this point is safe. 
Though, if you think this is premature, I wouldn't argue that, either.
> Captions 444

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/catalog_controller.rb
Looks good to me... might tweak the color scheme. 
@caseyedavis12 : Does this look good to you?
Fix #544
> out of the box range-limit gem

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/models/pb_core_spec.rb
Towards #536, but let's keep that open until there's data in and we've seen it work.
> Outside player links 536

- app/views/catalog/show.erb
@foo4thought: The anchor will be `#player`: You could add references to it now, and at some point it will be deployed.
> #player anchor. Fix #551.

- README.md
- app/models/pb_core.rb
- app/views/organizations/index.html.erb
- solr_conf/schema.xml
- spec/features/catalog_spec.rb
- spec/models/pb_core_spec.rb
Links from org page.
New facet, but not included on sidebar? ... Is that right?
Fix #543.
> View all results from state

- app/views/home/_browse_list.html.erb
- spec/features/homepage_spec.rb
fix #528: UI might change with input from Mike H, but something like this will still be in place.
> Add availability constraint to genre browse

- app/controllers/catalog_controller.rb
- config/environment.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/catalog_spec.rb
@afred: could you take a look at this approach to fix #377... Not sure how close this is to what we want.
> Multi facet 377

- app/controllers/exhibits_controller.rb
- app/models/exhibit.rb
- app/views/exhibits/index.erb
Fixes #517.
@caseyedavis12 : Looks like this: Let me know if there are problems.
> Exhibit index page

- config/featured/home-featured.yml
replaces old images, with images for records that will be in the ORR
> adds new images to gallery

- lib/tasks/ci.rake
> Adds conditional around :ci rake task

- app/models/pb_core.rb
- app/models/pb_core_instantiation.rb
- app/models/pb_core_name_role_affiliation.rb
- app/models/xml_backed.rb
- spec/models/pb_core_spec.rb
> Modularize pbcore 578

- app/assets/stylesheets/homepage.css
- app/assets/stylesheets/normalize.css
- app/views/home/show.html.erb
Adding a relative, sticky nav for the sections on the homepage
> Homepage Navigation

- app/models/pb_core.rb
- scripts/lib/pb_core_ingester.rb
... not sure why we did not see problems earlier? Maybe running on branch without this refactor?
> Script was failing with bad constant

- scripts/download_clean_ingest.rb
- scripts/lib/pb_core_ingester.rb
- spec/scripts/download_clean_ingest_spec.rb
- spec/scripts/pb_core_ingester_spec.rb
@afred: I think this does what you want? Fix #606.
> More ingest stats 606

- app/assets/stylesheets/application.css
- app/views/override/about-the-american-archive/staff.md
I've added all of the ones I have so far. @mccalluc: Can we merge this now, and I can add the rest when they come in later?
> Staff-pics

- app/views/catalog/show.erb
> reverse order of titles in sidebar.

- app/views/home/_browse_list.html.erb
- spec/features/homepage_spec.rb
Intern should [make edits](https://github.com/WGBH/AAPB2/blob/browse-collection-not-facets-620/app/views/home/_browse_list.html.erb) before merge, probably. @caseyedavis12 : in your court.
> Browse collection not facets 620

- app/controllers/catalog_controller.rb
- app/views/catalog/_facet_layout.html.erb
- spec/features/catalog_spec.rb
> Extra explanations on some facets, as requested by Casie. 

- spec/fixtures/pbcore/dirty-no-fix-multi-aai-id-error.txt
- spec/scripts/cleaner_spec.rb
> Do not test the full trace in the error message.

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/features/catalog_spec.rb
> Access control message 577

- app/views/catalog/_zero_results.html.erb
- spec/features/catalog_spec.rb
> Suggest folks broaden search if no results.

- app/controllers/thumbnails_controller.rb
- app/models/exhibit.rb
- app/views/catalog/_search_header.html.erb
- app/views/exhibits/show.erb
- app/views/exhibits/station-histories.md
- app/views/exhibits/station-histories/dedication-ceremonies.md
- app/views/exhibits/station-histories/first-broadcasts.md
- app/views/exhibits/station-histories/public-broadcasting-act.md
- app/views/exhibits/station-histories/restrospective-anniversaries.md
- spec/models/exhibit_spec.rb
> Style exhibits

- app/controllers/advanced_controller.rb
- config/environment.rb
- spec/features/catalog_spec.rb
> Facet ors 633

- app/views/catalog/_document_gallery.erb
- config/environment.rb
- lib/aapb.rb
not really happy with this, but was having a bigger headache trying to use other libraries.
> Infinite scroll on gallery

- config/initializers/session_store.rb
> Expire session after 1 hour, so TOS will be required again. 

- app/views/catalog/_zero_results.erb
I tried to reproduce this on localhost, and I tried producing a failing test, but I could not. Annoyed, but I think this is better, regardless.
> More robust no-results logic

- app/views/exhibits/station-histories.md
- app/views/exhibits/station-histories/dedication-ceremonies.md
- app/views/exhibits/station-histories/first-broadcasts.md
- app/views/exhibits/station-histories/public-broadcasting-act.md
- app/views/exhibits/station-histories/restrospective-anniversaries.md
The content from #693, but with the conflicts resolved.
> Resolve conflicts from Sadies PR.

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/features/catalog_spec.rb
- spec/rails_helper.rb
- spec/support/remote_ip_monkey_patch.rb
Fix #642
- @afred: Please review.
- @caseyedavis12 : um, I used a different message: This just seems really unclear to me.
> Content in the ORR is not currently available in your geography.
- Folks just landing on this page are not going to know what "ORR" means.
- "currently": I would wonder if this is a temporary outage or something longer term.
- I would have no idea what my "geography" is.
> Intl no access 642

- app/models/pb_core.rb
@afred : please review. Follow up to yesterday's PR.
> A little safer: Imagine getting a raw ampersand in URL

- app/controllers/advanced_controller.rb
- spec/controllers/advanced_controller_spec.rb
@afred: please review. Fixes #703... but worth looking at closely.
> Advanced search behavior closer to what we want... I think.

- app/assets/stylesheets/application.css
- app/views/exhibits/show.erb
@afred : please review. Fix #711.
- Fancy show-all
- Repeat the collection title here seems to make the most sense?
- Removed the hr and added a br
> Fancy show all.

- app/models/pb_core.rb
- spec/models/pb_core_spec.rb
> Remove vestigial code. Fix #569.

- Gemfile
- Gemfile.lock
- app/views/exhibits/climate-change/activism.md
- app/views/exhibits/climate-change/causes.md
- app/views/exhibits/climate-change/communicating-art.md
- app/views/exhibits/climate-change/debates.md
- app/views/exhibits/climate-change/history.md
- app/views/exhibits/climate-change/impacts.md
- app/views/exhibits/climate-change/solutions.md
- app/views/exhibits/station-histories/dedication-ceremonies.md
- app/views/exhibits/station-histories/first-broadcasts.md
- app/views/exhibits/station-histories/public-broadcasting-act.md
- app/views/exhibits/station-histories/restrospective-anniversaries.md
- spec/fixtures/exhibits/parent/child.md
- spec/fixtures/exhibits/parent/child/grandchild.md
- spec/fixtures/exhibits/parent/child/grandchild/greatgrandchild1.md
- spec/fixtures/exhibits/parent/child/grandchild/greatgrandchild2.md
- spec/models/exhibit_spec.rb
@afred: please review. Cmless now has inheritance.
> Md defaults

- config/featured/home-featured.yml
I realized that the Kincaid interview had a reading in it, so I switched it out for another vermont public television asset.
> switching-images

- config/vocab-maps/genre-type-map.yml
- config/vocab-maps/topic-type-map.yml
- lib/formatter.rb
- scripts/lib/cleaner.rb
- scripts/lib/pb_core_ingester.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-coverage-type-lc.xml
- spec/fixtures/pbcore/clean-empty-coverage-type.xml
- spec/fixtures/pbcore/clean-has-rights-already.xml
- spec/fixtures/pbcore/clean-no-identifier-source.xml
- spec/fixtures/pbcore/clean-no-instantiation-identifier-source.xml
- spec/scripts/cleaner_spec.rb
No effect till next reingest.
Fix #722.
> Move magazine, news report, and performance, as requested. 

- lib/html_scrubber.rb
- spec/lib/html_scrubber_spec.rb
Fix #728. Current scrubber is really trying to take off too much. @afred please review.
> Too much scrubbing

- app/models/user.rb
- spec/models/user_spec.rb
Adds tests for User#aapb_referer?
> Adds demo site as an allowed referer

- Gemfile
- Gemfile.lock
- scripts/lib/downloader.rb
- scripts/lib/pb_core_ingester.rb
- scripts/lib/zipper.rb
- spec/scripts/download_clean_ingest_spec.rb
- spec/scripts/zipper_spec.rb
@afred: please review. Fix #741
> Zip downloads 741

- Gemfile
- Gemfile.lock
- Rakefile
- app/controllers/robots_controller.rb
- scripts/download_clean_ingest.rb
- spec/scripts/download_clean_ingest_spec.rb
@afred: please review. Fixes #739
> purge blacklight-sitemap. Tests pass locally.

- app/views/override/about-the-american-archive/executive-advisory-council.md
Slightly different MD syntax between us and github: Could try using Githubs engine, if it really mattered. Fix #750.
> Execs now have a bullet list.

- app/views/catalog/_search_header.erb
- app/views/exhibits/civil-rights.md
- app/views/exhibits/civil-rights/rename-me.md
- spec/features/catalog_spec.rb
@caseyedavis12 : Merge this and then continue. 
(FWIW: Git abhors a vacuum: You can't actually create an empty directory.)
> Civil rights 764

- app/assets/stylesheets/blacklight.css.scss
- app/assets/stylesheets/exhibits.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_index_gallery.erb
- app/views/catalog/_search_header.erb
- app/views/exhibits/_show_all_items_header.html.erb
- app/views/exhibits/index.erb
- spec/features/catalog_spec.rb
closes #744 
@mccalluc please review
**UPDATE:** @mccalluc This PR had other stuff in it that we actually _do_ want right now. So please review, and refer to images below.
> 774 exhibit style tweaks

- app/views/override/about-the-american-archive/staff.md
> unsurpress margin below h4 so list is readable. Add Nick.

- app/assets/stylesheets/search_results.scss
@afred? Maybe you want more of the actual math inline? Assuming the end result is what we want?
> End result looks good to me. Fix #797?

- app/models/pb_core.rb
- app/views/catalog/show.erb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/models/pb_core_spec.rb
> External reference URLs. Fix #771.

- app/controllers/catalog_controller.rb
- app/controllers/embed_controller.rb
- app/controllers/embed_terms_controller.rb
- app/controllers/media_controller.rb
- app/controllers/terms_controller.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/catalog/_player.erb
- app/views/catalog/show.erb
- app/views/embed/show.erb
- app/views/layouts/embed.erb
- app/views/terms/show.erb
- config/routes.rb
- lib/aapb.rb
- spec/features/catalog_spec.rb
- spec/features/embed_spec.rb
@afred: One question is how the embedded TOS should be styled. Right now I'm not pulling in any CSS so it gets the browser default serif, but it could be different.
> Embed player 799

- app/models/pb_core.rb
- scripts/lib/cleaner.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-bad-essence-track.xml
- spec/fixtures/pbcore/clean-bad-language.xml
- spec/fixtures/pbcore/clean-bad-media-type.xml
- spec/fixtures/pbcore/clean-bad-relation-and-language.xml
- spec/fixtures/pbcore/clean-bad-title-type-substring.xml
- spec/fixtures/pbcore/clean-bad-title-type.xml
- spec/fixtures/pbcore/clean-basic.xml
- spec/fixtures/pbcore/clean-coverage-type-lc.xml
- spec/fixtures/pbcore/clean-empty-coverage-type.xml
- spec/fixtures/pbcore/clean-empty-description.xml
- spec/fixtures/pbcore/clean-every-title-is-episode-number.xml
- spec/fixtures/pbcore/clean-exhibit.xml
- spec/fixtures/pbcore/clean-has-rights-already.xml
- spec/fixtures/pbcore/clean-no-contributor.xml
- spec/fixtures/pbcore/clean-no-creator.xml
- spec/fixtures/pbcore/clean-no-identifier-source.xml
- spec/fixtures/pbcore/clean-no-instantiation-identifier-location-mediaType.xml
- spec/fixtures/pbcore/clean-no-instantiation-identifier-source.xml
- spec/fixtures/pbcore/clean-no-instantiation.xml
- spec/fixtures/pbcore/clean-no-publisher.xml
- spec/fixtures/pbcore/clean-no-relation-type.xml
- spec/fixtures/pbcore/clean-rename-attribute.xml
- spec/fixtures/pbcore/clean-sorting.xml
- spec/scripts/downloader_spec.rb
> "_" in IDs is now handled by Cleaner.

- app/controllers/captions_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/media_controller.rb
- app/controllers/thumbnails_controller.rb
- app/views/catalog/_index_gallery_default.erb
- app/views/catalog/_index_list_default.erb
> Simplify, as @afred suggested. Fix #784.

- app/views/terms/show.erb
Fix #830. It would be inappropriate to style this just like a title, because it's not, but other tweaks are possible. @afred?
> Extra explanatory blurb.

- app/models/exhibit.rb
- app/views/exhibits/civil-rights.md
- app/views/exhibits/civil-rights/organizations.md
- app/views/exhibits/civil-rights/people.md
- app/views/exhibits/civil-rights/places.md
- app/views/exhibits/climate-change.md
- app/views/exhibits/show.erb
- app/views/exhibits/station-histories.md
- spec/fixtures/exhibits/parent.md
- spec/models/exhibit_spec.rb
> New slot for extended html. Fix #833.

- app/views/exhibits/show.erb
> Exhibit search formatting 828 809

- app/views/home/_browse_list.erb
- app/views/home/show.erb
> blurbs. Fix #850.

- app/views/exhibits/_show_all_items_header.html.erb
@afred? Making a new branch with just the good part of #844. Fixes #827.
> Exhibit title on search page.

- app/controllers/catalog_controller.rb
- spec/features/catalog_spec.rb
until someone else needs to micromanage this. Fix #817. @afred?
> Back to default page sizes, 

- app/views/override/show.erb
- app/views/shared/_footer.erb
Fix #610, Fix #849: Added exhibit link at the same point in both lists. @afred?
> Link to exhibits

- app/assets/stylesheets/override.scss
- app/models/override.rb
- app/views/override/show.erb
@afred? Might also want to add some padding on the right? Maybe a new class just for these images?
> Pull-left every image. Fix #746.

- app/assets/stylesheets/homepage.scss
* Reduced padding of top homepage layer.
* Re-applies affixed navbar when scrolled down.
fixes #855
> Fixes style regression on homepage

- app/assets/stylesheets/override.scss
Fix #874. I'm not seeing the problem we had on #876. @afred?
> Fix bullet points, and nothing else in the header seems to change.

- app/views/exhibits/index.erb
- app/views/override/show.erb
- app/views/shared/_sidebar_nav.erb
since two separate instances need to show the same menu.
@afred: This fixes #872.
> Move the default menu items into the partial itself

- app/views/exhibits/station-histories/dedication-ceremonies.md
- app/views/exhibits/station-histories/first-broadcasts.md
- app/views/exhibits/station-histories/restrospective-anniversaries.md
@mccalluc I think this fixes the problem you were talking about. Can you verify? Thanks!
> Exhibition links

- app/views/shared/_footer.erb
I added the necessary comma. I would like to merge this update that includes "Blog" in the footer. It is OK that the logo that links to the blog is redundant.
> Add blog to footer

- app/views/exhibits/presidential-elections/notes.md
> Supply empty sections so that it does not inherit from the root. 

- app/views/exhibits/show.erb
> Only show the partial if there is something to show. fix #902.

- app/models/user.rb
The tweak to affirmed_tos feels sketchy, but fixes #894. @afred?
> Add hosts exception for popuparchive

- Gemfile
- Gemfile.lock
- spec/lib/geo_i_p_country_spec.rb
> Tests are passing for Chuck with this.

- app/views/override/help/contribute.md
- app/views/override/help/submit-metadata.md
- app/views/shared/_footer.erb
- app/views/shared/_header_navbar.erb
Collection acquisition form coming soon. Will upload to s3 tomorrow.
> Update and rename submit-metadata.md to contribute.md

- app/assets/javascripts/sticky.js
- app/assets/stylesheets/application.css
- app/views/shared/_sidebar_nav.html.erb
> sticky sidebar. Fixes #712.

- app/assets/stylesheets/application.css
> On every page except home there is a gap below the footer.

- app/views/override/about-the-american-archive/staff.md
> Changes to staff

- scripts/lib/downloader.rb
> Ignore bad key, since we do not have an ETA. Hack fix #949.

- solr_conf/schema.xml
- spec/solr/analysis_spec.rb
> Fix one small bug, and add low level test. Towards #946.

- README.md
I do not want to copy-and-paste everything from AAPB, but this is more accurate. Not sure about the future. One possibility is just keeping a brief outline here, and pointing at OV for the rest. Should there be a deploy.sh for this project as there is for OV?
@foo4thought ?
> Update deploy docs

- README.md
@caseyedavis12 : does this seem clear enough for the folks in Texas?
> Document OAI-PMH

- scripts/lib/downloader.rb
- spec/scripts/downloader_spec.rb
Will self merge after tests pass.
> Strengthen tests, ignore SSL everywhere.

- app/assets/javascripts/sticky.js
- app/assets/stylesheets/application.css
- app/views/shared/_sidebar_nav.html.erb
Reverts #927. @Muraszko or @caseyedavis12?
A general point about code reviews: You shouldn't just take my word that it does what I say it does. (Or that it even needs to be done.) 
Fixes #948 / Fixes #961.
> no more sticky sidebar

- app/controllers/thumbnails_controller.rb
> Unfreezes hash that gets modified

- app/controllers/catalog_controller.rb
- app/models/pb_core.rb
- app/models/to_mods.rb
- app/views/oai/index.xml.erb
- config/initializers/mime_types.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-MOCK.mods
> Oai tweaks

- app/assets/stylesheets/globals/normalize.css.scss
- app/assets/stylesheets/locals/media-tablet.css.scss
Towards #962. The CSS is really a mess, and I'm not sure how much ad-hoc tweaking we want to get into.
> Width weirdness

- Gemfile
- Gemfile.lock
- spec/aws/s3_spec.rb
- spec/fixtures/aws/bucket-policy.json
Security is less tight than OV, so this is a bit overkill. @Muraszko ?
> Fix #989 and test. 

- README.md
> Pointers on downloads via the API.

- app/views/catalog/show.html.erb
@foo4thought ? Fix #1016. Would you like to see capybara tests? Or maybe this should be pulled out of the view code?
> Quoted series titles 1016

- .rubocop_todo.yml
- scripts/download_clean_ingest.rb
- spec/scripts/download_clean_ingest_spec.rb
> Catch bad args. Lower rubocop standards. Fix #1017.

- app/models/pb_core.rb
- spec/support/link-check-ignore.txt
> remove erroneous comment in to_solr method

- app/assets/stylesheets/locals/catalog.css.scss
> Wrap longer IDs. Fix #721.

- app/models/user.rb
> allow AWS hosts to download media, hopefully.

- app/models/user.rb
> Fixes access for requests from popuparchive.com

- app/views/exhibits/first-amendment.md
- app/views/exhibits/first-amendment/notes.md
- app/views/exhibits/first-amendment/protests-60s-70s.md
- app/views/exhibits/first-amendment/protests-80s-andbeyond.md
- spec/support/link_checker.rb
@muraszko here you go. thank you.
> First amendment use this

- app/views/home/_featured_carousel.html.erb
> 1077 - Disables turbolinks for links from featured_carousel

- app/models/exhibit.rb
- app/views/exhibits/first-amendment.md
- app/views/exhibits/first-amendment/notes.md
- app/views/exhibits/first-amendment/protests-60s-70s.md
- app/views/exhibits/first-amendment/protests-80s-andbeyond.md
> First amendment fixes 

- app/views/exhibits/first-amendment/protests-80s-andbeyond.md
> Fix Schlafly misspelling

- lib/caption_converter.rb
@afred - as_timestamp method in CaptionConverter class was choking on nil time values.
Closes #1152
> 1152: 500 Errors

- lib/caption_converter.rb
> Call Rails.logger.warn instead of Rails.warn

- .gitignore
- app/assets/stylesheets/globals/normalize.css.scss
- app/views/advanced/index.html.erb
- app/views/catalog/_facet_layout.html.erb
- app/views/catalog/_index_header_default.html.erb
- app/views/catalog/_search_form.html.erb
- app/views/catalog/_search_form_big.html.erb
- app/views/home/_carousel.html.erb
- app/views/home/show.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_sidebar_nav.html.erb
@afred - Defines website regions on AAPB for accessibility. Some of the work was already done here - a big one, the "main" section, was already defined. Checked views across browsers with Safari. Closes #1087
> 1087 Website Regions

- app/assets/stylesheets/globals/blacklight_overrides.css.scss
- app/assets/stylesheets/globals/homepage.css.scss
- app/assets/stylesheets/globals/normalize.css.scss
- app/views/catalog/_facet_layout.html.erb
- app/views/catalog/_facets.html.erb
- app/views/exhibits/index.html.erb
- app/views/home/_blog.html.erb
- app/views/home/_browse_list.html.erb
- app/views/home/_orgs_map.html.erb
- app/views/home/show.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/organizations/index.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_sidebar_nav.html.erb
@afred - Implements NCAM's accessibility recommendations. Based on their report and Casey's notes.
> 1085: Sequential Headings

- app/views/shared/_footer.html.erb
> Add organizations to footer

- config/states.yml
for states with multiple NAEB stations
> hard coded blurbs

- app/assets/stylesheets/locals/carousel.css.scss
- app/views/home/_carousel.html.erb
@afred - This adds a play/pause button to the homepage carousels. Closes #1081.
> 1081: Gallery Controls

- app/assets/stylesheets/globals/blacklight_overrides.css.scss
- app/views/catalog/_facet_layout.html.erb
- app/views/catalog/_facets.html.erb
@afred - this makes the top-level facet names on the catalog index in to li items.
* Also tweaks styles to match current style
* Closes #1086
> 1086: Makes top level facet dropdowns in to <li>s

- app/models/pb_core.rb
- spec/features/api_spec.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-transcript.xml
- spec/models/pb_core_spec.rb
- spec/scripts/download_clean_ingest_spec.rb
- spec/scripts/pb_core_ingester_spec.rb
@afred - Ready for review! This takes the PopUp Archive transcripts from S3 and indexes them in the Solr Document text field for search. Closes #1098
> 1098 pua transcripts

- app/models/caption_file.rb
* Uses regex for more precise word parsing
* Also fixes logic falsely returning nil
* Closes #1055 
@afred
> 1055: Fixes Incorrect Caption Highlighting

- app/views/override/about-the-american-archive/projects.md
Needs to be merged with this next redeploy
> Add pbcore to projects page

- config/states.yml
> Fixes state abbr in states.yml

- app/models/pb_core.rb
> Requires fastimage for PBCore model

- app/views/catalog/_rules_of_use_modal.html.erb
> Auto reload page after agreeing to TOS

- app/assets/stylesheets/globals/homepage.css.scss
- app/views/home/_fixit.html.erb
- app/views/home/show.html.erb
- app/views/layouts/blacklight.html.erb
- spec/support/validation_helper.rb
@afred - Adds the Fix It section to the AAPB homepage and reorders section. Closes #1240 #1177
> 1177: Fix It Section on Homepage

- lib/caption_converter.rb
- spec/features/api_spec.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-invalid-captions.xml
- spec/lib/caption_converter_spec.rb
- spec/scripts/pb_core_ingester_spec.rb
- spec/support/link-check-ignore.txt
> 1265 srt exception

- app/assets/javascripts/player.js
@afred - This autoplays video on catalog#show if timecode included in URL. It's an extension of the transcript play button functionality. Closes #1266
> Plays video from timecode included in URL

- app/views/exhibits/newsmagazines/precedents.md
Moved image to correct section in newsmag exhibit
> Update precedents moving image to correct section

- app/assets/stylesheets/locals/catalog.css.scss
- app/models/pb_core.rb
- app/models/xml_backed.rb
- app/views/catalog/_player.html.erb
- solr_conf/schema.xml
- spec/features/api_spec.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-playlist-1.xml
- spec/fixtures/pbcore/clean-playlist-2.xml
- spec/fixtures/pbcore/clean-playlist-3.xml
- spec/models/pb_core_spec.rb
- spec/scripts/pb_core_ingester_spec.rb
@afred - This implements an OpenVault-style playlist functionality. Pretty straightforward implementation. Thanks! Closes #1290.
> 1290: AAPB Playlists

- app/views/shared/_footer.html.erb
> 1296: Opens External Links in New Window in Footer

- app/assets/javascripts/player.js
- app/views/catalog/_player.html.erb
- app/views/catalog/_transcript.html.erb
@afred - catalog#show starts with an open transcript viewer if there is a transcript available. Closes #1287.
> 1287: Shows Transcript By Default When Available

- app/assets/stylesheets/locals/catalog.css.scss
- app/assets/stylesheets/locals/transcript.css.scss
@afred - Ready for review. Reduces space beneath the player a smidge.
* Closes #1298
* Also increases transcript window to better match video player height.
> 1298: Reduces Space Beneath Player

- app/assets/stylesheets/globals/normalize.css.scss
@afred - Removes CSS that was cutting off Advanced Search form
> 1321: Advanced Search Form

- app/views/layouts/blacklight.html.erb
- app/views/override/about-the-american-archive/newsletter.md
- app/views/override/contact-us.md
- app/views/override/donate.md
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_sidebar_nav.html.erb
- spec/support/validation_helper.rb
@afred - Creates newsletter signup page and adds to navigation. 
- Closes #1222  
- Also adds links to Contact and Donate pages
> 1222: Newsletter Signup Page

- app/assets/stylesheets/locals/player.css.scss
- app/views/catalog/_player.html.erb
- config/vocab-maps/title-type-map.yml
- spec/features/catalog_spec.rb
@afred - Sorts "segment" last in title construction during ingest. This will require reingest of records to take effect.
* Also tweaks CSS to fix small issue with playlists and exhibits
* Closes #1327
> 1327: Title Display

- app/assets/stylesheets/locals/navigation.css.scss
- app/views/catalog/_search_form.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
@afred - adds advanced search link to search bar in header and to footer.
* Closes #1254
> 1254: Adds Advanced Search

- app/views/catalog/_constraints.html.erb
- app/views/catalog/index.html.erb
@afred:
* Changes title in header to "Search Results"
* Changes "Start Over" to "Clear Search"
* Closes #1122
* Closes #1130
> Changes title and start over text on search results page

- app/assets/javascripts/application.js
- app/assets/javascripts/catalog-index.js
- app/assets/stylesheets/locals/catalog.css.scss
- app/views/catalog/_per_page_widget.html.erb
- app/views/organizations/md/NCSG55087.md
- config/initializers/assets.rb
@afred - This displays a rotating "loading" icon when the user updates the sorting or per page options. Also includes an abbreviation fix for LOC org page that just cropped up in my manual testing.
> 1257 Loading Icon

- app/views/override/about-the-american-archive/funding.md
- app/views/override/about-the-american-archive/projects.md
- app/views/override/about-the-american-archive/projects/mellon.md
> Mellon info

- app/models/pb_core.rb
- app/models/transcript_file.rb
- spec/models/transcript_file_spec.rb
@afred - this updates the to_solr on pb_core.rb to process both json and text transcripts. Closes #1344.
> 1344: Index Non Popup Archive Transcripts

- app/assets/stylesheets/locals/catalog.css.scss
- app/models/pb_core.rb
- app/views/catalog/show.html.erb
- spec/features/api_spec.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-supplemental-materials.xml
- spec/models/pb_core_spec.rb
- spec/scripts/pb_core_ingester_spec.rb
@afred - this PR adds a "Supplemental Materials" section to the catalog#show page and a new fixture for testing it. Styles were approved by @sroosa.
* Closes #1340
> Adds Supplemental Materials to catalog#show

- app/views/home/show.html.erb
> Adds Special Collections to stickynav

- app/views/exhibits/show.html.erb
* Closes #1383
* Still includes link to all items per page
> Removes Exhibit gallery

- app/views/special_collections/_search_results.html.erb
* Hides terms if not included on Special Collection page
* Closes #1384
> Hides Suggested Terms from Special Collection search results

- app/assets/javascripts/application.js
- app/assets/javascripts/background-video.js
- app/assets/stylesheets/globals/homepage.css.scss
- app/views/home/show.html.erb
- config/initializers/assets.rb
@afred - for when you get chance to review. not urgent, i don't think. it just adds a play/pause button for the homepage background video we added with the last release. this is for accessibility.
Design approved on ticket.
Closes #1385.
> 1385: Completes Play|Pause for Homepage BG Video

- app/views/special_collections/woman-series.md
> Woman special collection

- app/models/organization.rb
- app/views/organizations/md/NCSG088.md
> 1429-stanford-to-hoover

- app/views/special_collections/american-masters-interviews.md
- app/views/special_collections/woman-series.md
Fixed some typos and formatting issues
> Special collection p

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/locals/embed.css.scss
- app/views/embed/show.html.erb
- app/views/layouts/embed.html.erb
Limits the data in the embeddable player view and brings in styling to make it more responsive. Closes #1449.
> Completes Styling for Embedded Video View

- config/vocab-maps/date-type-map.yml
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-basic.xml
> Updates 'Copyright' label to 'Copyright Date'

- app/assets/stylesheets/locals/catalog.css.scss
- app/views/catalog/_player.html.erb
- spec/support/link-check-ignore.txt
> Completes video loading background

- app/views/override/about-the-american-archive/whats-new.md
Updated image calls and sizing, as well as added a credit to the "pennstationcrop.jpg" because it belongs to LOC. Please review that.
> Update to Whats New Page - Ryn

- app/views/override/legal/orr-rules.md
- app/views/plain_override/rules-of-use.md
> Update orr rules

- app/views/organizations/md/1817.md
I'm not sure if this will break anything. I don't think the markdown gets validated to only have one url, but I'm not sure how it will display.
> adds second url

- app/views/organizations/md/NCSG55089.md
- app/views/organizations/md/NCSG55090.md
- app/views/organizations/md/NCSG55091.md
- app/views/organizations/md/NCSG55092.md
- app/views/organizations/md/NCSG55093.md
- app/views/organizations/md/NCSG55095.md
@afred - Adds new organizations to AAPB.  
* Closes #1485
> New organizations

- app/assets/stylesheets/globals/header.css.scss
- app/views/override/help/station-communications-toolkit.md
- spec/support/link-check-ignore.txt
Adding station communications toolkit
> Adding station communications toolkit

- app/views/override/about-the-american-archive/advisory-committees.md
> AAPB Advisory Committees 

- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_sidebar_nav.html.erb
> Adds new pages to menus

- app/views/special_collections/aapb-road-trip.md
- app/views/special_collections/net-catalog.md
- app/views/special_collections/show.html.erb
- spec/support/link-check-ignore.txt
> Hides Featured Items if None Included

- app/views/embed/show.html.erb
- spec/features/embed_spec.rb
Updates how we pull organizations off the PBCore document to match recent updates. Adds a basic feature test to help catch this in the future.
> Fixes embed#show

- app/views/special_collections/vision-maker-media.md
> Vision maker media collection

- app/views/special_collections/caam-collection.md
> Caam Special Collection

- Gemfile.lock
- app/assets/stylesheets/locals/banners.css.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_catalog_title_main.html.erb
- app/views/catalog/_player.html.erb
- app/views/catalog/_player_container.html.erb
- app/views/catalog/show.html.erb
- app/views/special_collections/georgia-gazette.md
- spec/support/link-check-ignore.txt
> 1543 show special collection banner

- README.md
@afred - this updates the command for the complete ingest on production in the README.
> Updates README for production ingest

- app/views/special_collections/caam-collection.md
- app/views/special_collections/georgia-gazette.md
- app/views/special_collections/jubilee-singers-interviews.md
- app/views/special_collections/oeta-news-cultural-programming.md
- spec/support/link-check-ignore.txt
Reverts WGBH/AAPB2#1572
Oops! Clicking too many buttons!
> Revert "1570 imls logo"

- app/views/special_collections/1964-interviews.md
- app/views/special_collections/american-masters-interviews.md
- app/views/special_collections/reconstruction-interviews.md
- app/views/special_collections/the-abolitionists-interviews.md
- spec/support/link-check-ignore.txt
Its been a bit since the last time I issued a pull request, so let me know if I have to change anything!
> American experience 2

- app/models/user.rb
- app/views/catalog/_player.html.erb
> Upgrade video js

- app/views/organizations/index.html.erb
- app/views/organizations/show.html.erb
- spec/features/organizations_spec.rb
This is failing on a test fixed in another branch with a PR.
> 1591 - Updates link to view all records from organization page

- app/views/layouts/embed.html.erb
> 'bump up embed layouts old vjs version'

- app/views/special_collections/newshour.md
Fix NewsHour collection other resources
> Fix NewsHour collection other resources

- app/views/special_collections/kopn-women.md
- app/views/special_collections/northcarolinavoices.md
- app/views/special_collections/oeta-news-cultural-programming.md
- app/views/special_collections/stonewall-uprising.md
Consolidates all the open markdown PRs.
> Consolidate markdown

- app/assets/stylesheets/locals/catalog.css.scss
- app/assets/stylesheets/locals/player.css.scss
- app/controllers/catalog_controller.rb
- app/views/catalog/_player.html.erb
- app/views/catalog/_rules_of_use_modal.html.erb
- spec/fixtures/pbcore/clean-exhibit.xml
- spec/fixtures/pbcore/clean-has-chapters.xml
- spec/models/pb_core_spec.rb
> 1642 AAPB Fixes

- app/assets/stylesheets/globals/exhibits.css.scss
- app/controllers/exhibits_controller.rb
> 1647 Exhibit QA

- app/views/special_collections/en-francais.md
Create new En Francais collection
> En francais collection

- lib/transcript_converter.rb
- spec/lib/transcript_converter_spec.rb
-Cleans up some old stuff in TranscriptFile
-Protects against case where there is a valid, but empty, JSON transcript
> 'delete old func, return nil when no json_parts, add test'

- app/assets/stylesheets/globals/basic_modal.css.scss
- app/controllers/catalog_controller.rb
- app/models/pb_core.rb
- app/views/catalog/_player.html.erb
- app/views/special_collections/_collection_search.html.erb
- solr_conf/schema.xml
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-special_collection.xml
- spec/models/pb_core_spec.rb
**WAIT TO MERGE!** get 👍 from @sroosa first.
The first commit is for something small I caught while poking around Special Collections which is that the text in "Need Help Searching" modal from Special Collections wasn't getting contained with the modal. This fix just sets the overflow property so that the text scrolls in the modal.
The second commit is for the actual ticket to make Special Collections multivalued on our records.
> 1708 Special Collections

- app/views/organizations/usa.svg
- config/states.yml
> removing NAEB stations from participating org list and map

- app/views/catalog/show.html.erb
> Updates mailto on catalog#show

- app/assets/stylesheets/globals/exhibits.css.scss
- app/views/exhibits/show.html.erb
> 1748 exhibit read more

- config/routes.rb
> Redirects NET static pages to SpecialCollection

- spec/controllers/thumbnails_controller_spec.rb
- spec/features/catalog_spec.rb
- spec/features/media_spec.rb
- spec/features/oai_spec.rb
- spec/features/transcripts_spec.rb
- spec/fixtures/aws/bucket-policy.json
- spec/scripts/pb_core_ingester_spec.rb
* Also comments out loading fixtures in tests that don't require them.
* Also updates bucket policy fixture
> xit tests based on blacklight facet behavior

- app/assets/stylesheets/locals/search-results.css.scss
- app/models/search_builder.rb
- app/views/catalog/_date_range_filter.html.erb
- app/views/catalog/_facets.html.erb
- solr_conf/schema.xml
> Fix Date Range Facet CSS and 'Exact Date' Range Handling

- spec/models/special_collection_spec.rb
de loops models/special_collection_spec.rb
> Completes special collection spec refactor

- app/models/pb_core_presenter.rb
- spec/models/pb_core_spec.rb
This PR relies on https://github.com/WGBH-MLA/AAPB2/pull/1793. We need to merge that one first.
> 1780 deloop pbcore spec

- app/views/special_collections/_collection_search.html.erb
When going to the "View the Collection" search results page for a Special Collection the results are sorted ascending by asset_date.
> Sorts by asset_date asc

- app/views/organizations/md/NCSG55102.md
- app/views/organizations/md/NCSG55103.md
- app/views/organizations/usa.svg
Closes #1809 and Closes #1823 and Closes #1810
> adds sesame and thinktv pages and updates map

- app/assets/stylesheets/locals/gallery.css.scss
- app/assets/stylesheets/locals/media-mobile.css.scss
- app/views/special_collections/index.html.erb
Moves title from an overlay to beneath the thumbnail. It also sets dimensions on the title so that the columns stack correctly.
> Moves title on SpecialCollection index

- app/views/special_collections/lgbt.md
> Update LGBT+ collection

- app/views/override/about-the-american-archive/executive-advisory-council.md
Moves Cokie Roberts to past council members.
> Update EAC page

- Gemfile
- Gemfile.lock
- app/assets/javascripts/affix.js
- app/assets/javascripts/application.js
- app/assets/javascripts/background-video.js
- app/assets/javascripts/global/datepicker.js
- app/assets/javascripts/mobile-transcript.js
- app/assets/javascripts/player.js
- app/assets/javascripts/rules-modal.js
- app/assets/javascripts/transcript.js
- app/views/catalog/_access_facet.html.erb
- app/views/catalog/_date_range_filter.html.erb
- app/views/catalog/_per_page_widget.html.erb
- app/views/catalog/_player.html.erb
- app/views/catalog/accordion/_accordion.html.erb
- app/views/exhibits/_gallery.html.erb
> Removes Turbolinks

- app/controllers/catalog_controller.rb
- app/models/pb_core_presenter.rb
- solr_conf/schema.xml
- spec/models/pb_core_spec.rb
> Adds Sorting by Episode Number

- app/models/ability.rb
- app/models/pb_core_presenter.rb
- spec/fixtures/pbcore/clean-transcript.xml
- spec/models/abilities/pbcore/can_access_transcript_spec.rb
> 1831 Requires a transcript status on Ability to view transcript

- app/controllers/captions_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/transcripts_controller.rb
- app/models/caption_file.rb
- app/models/pb_core_presenter.rb
- app/models/solr_document.rb
- app/models/transcript_file.rb
- lib/caption_converter.rb
- spec/features/catalog_spec.rb
- spec/fixtures/pbcore/clean-multiple-producing-orgs.xml
- spec/fixtures/pbcore/clean-playlist-2.xml
- spec/fixtures/pbcore/clean-special_collection.xml
- spec/fixtures/pbcore/clean-text-transcript.xml
- spec/models/caption_file_spec.rb
- spec/models/pb_core_spec.rb
- spec/models/transcript_file_spec.rb
- spec/scripts/download_clean_ingest_spec.rb
This PR changes Captions and Transcripts to directly use the 3s URLs from the PBCore.
> 1848 Captions & Transcripts

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/helpers/snippet_helper.rb
- spec/models/caption_file_spec.rb
- spec/models/transcript_file_spec.rb
Updates the SnippetHelper to process query terms with quotes for exact searching.
> 1724 Transcript/Caption Search Highlights

- app/assets/javascripts/player.js
- app/assets/stylesheets/locals/catalog.css.scss
- app/assets/stylesheets/locals/player.css.scss
- app/views/catalog/_player.html.erb
- app/views/catalog/_share_modal.html.erb
Adds a link share and embed code in a modal on catalog#show.
> 1885 Adds a Modal for Sharing Videos

- app/views/exhibits/conservatism/politics-net.md
Replace image URL with correct image.
> Fix image link

- config/routes.rb
- public/educator_resources.html
Adds an under construction page for /educator_resources for a conference.
> Resources Construction Page

- config/featured/home-featured.yml
Maybe we can get this in to today's release?
> Update homepage featured carousel

- config/featured/home-featured.yml
> Alan fixes

- app/assets/javascripts/player.js
Add back in code to handle `#at_<time>_s` URLS. Coexists with 'make a clip' slider.
> 1984 readd at time s

- app/views/special_collections/freedom-riders-interviews.md
Adds link from Freedom Riders collection to the resources on PBS Learning Media
> Add link to learning media

- app/views/special_collections/jahm.md
Fixes catalog sorting and link to jahm.us
> JAHM Collection Fixes

- app/controllers/catalog_controller.rb
- app/controllers/media_controller.rb
- app/controllers/thumbnails_controller.rb
- app/helpers/blacklight_guid_fetcher.rb
- app/helpers/id_helper.rb
- app/helpers/solr_guid_fetcher.rb
- app/models/pb_core_presenter.rb
- app/models/validated_pb_core.rb
- app/views/catalog/show.html.erb
- scripts/lib/pb_core_ingester.rb
- spec/controllers/thumbnails_controller_spec.rb
- spec/cors/cors_spec.rb
- spec/features/api_spec.rb
- spec/features/catalog_spec.rb
- spec/features/media_spec.rb
- spec/features/oai_spec.rb
- spec/features/transcripts_spec.rb
- spec/fixtures/pbcore/clean-MOCK.mods
- spec/fixtures/pbcore/clean-MOCK.xml
- spec/fixtures/pbcore/clean-has-captions.xml
- spec/fixtures/pbcore/clean-invalid-captions.xml
- spec/fixtures/pbcore/clean-moving-image-private.xml
- spec/fixtures/pbcore/clean-moving-image-protected.xml
- spec/fixtures/pbcore/clean-moving-image-public.xml
- spec/models/pb_core_spec.rb
- spec/scripts/cleaner_spec.rb
This extends the work on GUID normalization, mainly to address issues with downloading media media by ID on the site.
> More Guid Normalization

- app/assets/stylesheets/globals/homepage.css.scss
- app/views/home/_help_us.html.erb
Approved approach for updating the Help Preserve Public Media section on the homepage.
> Updates Help Preserve Section on Homepage

- app/models/pb_core_presenter.rb
> Uniq the Xhibit

- app/helpers/application_helper.rb
(For caption/transcript highlighting)
> Delete stopwords when found in queries that contain quoted clauses

- app/assets/javascripts/transcript.js
- app/controllers/catalog_controller.rb
- spec/features/catalog_spec.rb
fixes transcript viewer scrollTo, covers bad id case on catalog#show
> Fix Transcript Viewer ScrollTo, Handle 404 case on CatalogController#show

- app/assets/stylesheets/locals/navigation.css.scss
- app/models/xml_backed.rb
Had to add another CData check for another XMLBacked method. Also, the CSS border radius on the Fix It Plus logo in the AAPB header has been bugging me, so I made a tweak to logo size and CSS that fixes it.
> More CDATA Fixes

- app/controllers/forms_controller.rb
- app/views/forms/volunteer.html.erb
- app/views/shared/_header_navbar.html.erb
- config/routes.rb
Adds Volunteer Form with embedded Google form. Closes #2099
> Adds Volunteer Form

- app/views/organizations/md/NCSG55098.md
Adds logo and about text for Nashville Public Television.
> Adds logo and "About" text to NPT

- app/models/organization.rb
- spec/models/organization_spec.rb
This PR adds the ability for the Organization class to check for any digitized records associated with that organization so that we can link to digitized records or all records depending on the result.
> 2118 Organization All Records Link

- app/views/exhibits/presidential-elections/candidates.md
Thanks to the great work of intern Declan McBride. Let's launch this to demo today and to production tomorrow after QC in time for tomorrow night's debate. Let's also launch the Prospects of Mankind and People Near Here special collections which should be ready to go.
> Add NewsHour appearances

- app/views/exhibits/presidential-elections.md
- app/views/exhibits/presidential-elections/candidates.md
> Presidential fix

- scripts/the_pbcore_corrector.rb
ThePBCoreCorrector rewrites titleTypes and descriptionTypes that have been mistakenly indexed as a source attribute. The class takes an array of GUIDs and run the process.
> 2171 Rewrite/Reindex PBCore

- lib/tasks/transcripts.rake
- lib/transcript_downloader.rb
- spec/lib/transcript_downloader_spec.rb
There was an issue on production that required us to actually download the transcript files before zipping them.
> Refactors TranscriptDownloader

- app/views/special_collections/vision-maker-media.md
Fix broken link in featured items
> Fix broken link

- lib/ci_to_aws_transfer.rb
- spec/lib/ci_to_aws_transfer_spec.rb
This script takes a solr query and moves the media files for all records found to a directory on s3.
> 2188 Ci to s3

- app/views/organizations/md/1784.2.md
Adds final copy for GBH rebrand to GBH org md file.
> Copy rebrand-approved GBH Org 'About' Text

- app/views/exhibits/watergate.md
- app/views/special_collections/watergate.md
Adds Kathryn Brownell article to Watergate exhibit and special collection
> Update watergate resources

- app/views/organizations/md/1344.md
- app/views/organizations/md/1798.md
> Updates org pages for MPB and WGCU

- app/views/special_collections/fridaynightjazz.md
- config/routes.rb
making the Friday Night Jazz special collection! ready to be pushed now!
> Fridaynightjazz

- app/views/catalog/show.html.erb
- app/views/override/faq.md
- app/views/override/metadata-transcripts.md
- app/views/shared/_footer.html.erb
Adds new metadata and transcripts statement page, section of FAQ, link in Footer, and link in box that appears on record pages.
> Metadata transcripts statement

- app/views/special_collections/9-11-special-coverage.md
New 9/11 special coverage special collection is ready to be reviewed. @mivillesvik is adding annotations to the selected records.
> 9 11 special coverage

- app/views/override/about-the-american-archive/podcast.md
Image file: https://drive.google.com/file/d/1SumXbvZLaAzpyENJFZz-Iqyz8wopk2yi/view?usp=sharing
> Launching podcast.md

- app/views/override/about-the-american-archive/metadata-transcripts.md
Adds content warning to metadata and transcripts statement.
> Adds content warning

- app/views/shared/_footer.html.erb
For the content warning statement
> Update footer with broader language

- app/views/special_collections/peabody.md
The text we previously had wasn't showing up so I replaced with logo formatted correctly using PBS NewsHour as example.
> Nhprc logo

- app/views/exhibits/eotp.md
- app/views/exhibits/eotp/1-framing-civil-rights-past.md
- app/views/exhibits/eotp/2-making-television-history.md
- app/views/exhibits/eotp/3-timeline-of-events.md
- app/views/exhibits/eotp/4-locating-the-movement.md
- app/views/exhibits/eotp/5-1-local-people.md
- app/views/exhibits/eotp/5-2-women.md
- app/views/exhibits/eotp/5-3-organizational-activists.md
- app/views/exhibits/eotp/5-4-officials.md
- app/views/exhibits/eotp/5-5-media.md
- app/views/exhibits/eotp/5-6-religious-leaders.md
- app/views/exhibits/eotp/5-7-labor-business.md
- app/views/exhibits/eotp/5-8-students-educators.md
- app/views/exhibits/eotp/5-interview-subjects.md
> Adding "Presenting the Past" Podcast to the EOTP Exhibit

- app/views/override/about-the-american-archive/webinars.md
Adds an about page for webinars AAPB has hosted.
> Adds Page for Webinars

- app/views/organizations/usa.svg
Adds pins for cities in KS and NM to the participating organizations map here: https://americanarchive.org/participating-orgs
> Adds pins for NM and KS

- app/views/organizations/md/1708.md
Copied from Jason's accidentally-closed PR.
> Updates Arkansas PT org page

- app/views/catalog/_player.html.erb
- app/views/embed/show.html.erb
> Change verbiage for On-location and Private items

- app/helpers/snippet_helper.rb
- spec/features/catalog_spec.rb
- spec/features/embed_spec.rb
- spec/helpers/snippet_helper_spec.rb
> Guard against bad params in SnippetHelper

- app/models/pb_core_presenter.rb
- app/views/catalog/_index_header_default.html.erb
- app/views/catalog/accordion/_description.html.erb
- spec/features/api_spec.rb
- spec/fixtures/pbcore/clean-desc-date-sort.xml
- spec/models/pb_core_spec.rb
Adds specific sorting and labels for an asset's descriptions and dates on catalog#show. Closes #2288
> Adds specific sorting and labels for asset dates and descriptions

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/controllers/media_controller.rb
- app/views/catalog/_player.html.erb
- lib/ci_to_aws_transfer.rb
- lib/transcript_converter.rb
- spec/lib/ci_to_aws_transfer_spec.rb
Reverts WGBH-MLA/AAPB2#2354
something broke
> Revert "2346 switch to streaming"

- app/views/override/about-the-american-archive/podcast.md
Adds updated podcast.md for AAPB Podcast Episode 005.
> Add Info For Podcast Episode 005

- app/views/special_collections/zoom.md
> Zoom specialcollection

- app/views/override/about-the-american-archive/podcast.md
Ready to launch Jean Walkinshaw!
> Ep7 walkinshaw

- app/views/override/about-the-american-archive/podcast.md
> Fix podcast page

- app/views/override/about-the-american-archive/executive-advisory-council.md
Please release to the public site, thanks!
> Add Joanne Griffith

- app/views/exhibits/newshour-cold-war.md
@foglabs sorry I didn't catch this earlier!!
> Little fix to block quote

- app/views/exhibits/newshour-cold-war.md
@foglabs Alan asked for this image to be tweaked
> Update signature image

- app/models/pb_core_presenter.rb
- spec/models/pb_core_spec.rb
> Fixes error when transcript file is missing

- app/views/exhibits/conservatism.md
- app/views/special_collections/eotp-i-interviews.md
- app/views/special_collections/jean-walkinshaw.md
- app/views/special_collections/kut-in-black-america.md
- app/views/special_collections/linea-abierta.md
- app/views/special_collections/newtonminow.md
- app/views/special_collections/radio-kdna.md
- app/views/special_collections/vision-maker-media.md
Adds podcasts to relevant collections and exhibits
> Podcast visibility

- app/views/override/about-the-american-archive/podcast.md
> New PTP podcast episode with Judy Woodruff and Annette Miller

- .github/workflows/aapb-ci.yml
- app/views/special_collections/new-mexico-public-media-collection.md
NM special collection! I'm adding the special collection annotations over the weekend, so those should hopefully be done by the time we're back on Tuesday!
> Nm publicmediacollection

- app/views/exhibits/conservatism.md
- app/views/exhibits/eotp.md
- app/views/exhibits/latino-empowerment.md
- app/views/override/about-the-american-archive/podcast.md
- app/views/special_collections/jean-walkinshaw.md
- app/views/special_collections/kut-in-black-america.md
- app/views/special_collections/linea-abierta.md
- app/views/special_collections/newshour.md
- app/views/special_collections/newtonminow.md
- app/views/special_collections/radio-kdna.md
- app/views/special_collections/vision-maker-media.md
Changes youtube links to podcast episodes
> Podcast link update

- app/views/special_collections/wpln-the-fine-print.md
WPLN The Fine Print from PBPF Fellow Ryan Inman is ready to go!
> Wpln the fine print

- app/views/special_collections/black-champions.md
> Black champions

- app/controllers/catalog_controller.rb
Show 20 results by default when no option selected.
Closes #2451
> Default 20 search results per page

- app/views/organizations/usa.svg
Adds station dot for KERA in Dallas, TX
Closes #2345
> Add KERA (Dallas, TX) to `participating-orgs` map

- app/views/exhibits/eotp.md
- app/views/exhibits/latino-empowerment.md
- app/views/override/about-the-american-archive/podcast.md
> Remove GBH logo from embed

- app/views/primary_source_sets/black-power.md
- app/views/primary_source_sets/busing-boston.md
- app/views/primary_source_sets/great-depression.md
Fixes broken links using old URLs with underscores
> Primary source links

- .github/ISSUE_TEMPLATE/Because_Done.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Swaps github `:emoji:` syntax to full emoji in issue template name
> Fix issue template names to display titles properly

- app/helpers/blacklight_guid_fetcher.rb
Fixes Jira ticket AAPB-54
Closes #2454
> Add Rows Option For Solr Searches In SnippetsController AAPB-54

- app/views/primary_source_sets/busing-boston.md
- app/views/primary_source_sets/great-depression.md
Adds Bunk collections to Additional Resources on primary source sets.
> Bunk resources

- app/controllers/catalog_controller.rb
https://helpdesk.wgbh.org/browse/MLATT-18
> Show 'view' or 'listen to' on shared segment based on media type

- app/views/special_collections/en-francais.md
- app/views/special_collections/show.html.erb
and fix thumbnail urls for en-francais special collection
> Move Featured Items into Right-Side Column

- app/views/primary_source_sets/student-protests.md
- app/views/primary_source_sets/student-protests/1-28-ft8df6kf9j.md
- app/views/primary_source_sets/student-protests/2-15-j678s4jx9p.md
- app/views/primary_source_sets/student-protests/3-516-gq6qz23f5j.md
- app/views/primary_source_sets/student-protests/4-305-56zw3x5p.md
- app/views/primary_source_sets/student-protests/5-500-zw18r57g.md
- app/views/primary_source_sets/student-protests/6-516-gq6qz23f5j.md
- app/views/primary_source_sets/student-protests/7-3a9669d8374.md
- app/views/primary_source_sets/student-protests/8-feb446b0de5.md
Waiting for all transcripts to be corrected, then it should be ready to go live.
> Mpsds student protests

- app/views/primary_source_sets/american-indian-movement.md
- app/views/primary_source_sets/american-indian-movement/1-28-rb6vx06h40.md
- app/views/primary_source_sets/american-indian-movement/10-293-9s1kh0f775.md
- app/views/primary_source_sets/american-indian-movement/2-224-257d81km.md
- app/views/primary_source_sets/american-indian-movement/3-28-wh2d795w2v.md
- app/views/primary_source_sets/american-indian-movement/4-28-q23qv3cj2p.md
- app/views/primary_source_sets/american-indian-movement/5-28-p843r0q996.md
- app/views/primary_source_sets/american-indian-movement/6-15-78gf28x2.md
- app/views/primary_source_sets/american-indian-movement/7-28-hq3rv0db64.md
- app/views/primary_source_sets/american-indian-movement/8-207-483j9qpk.md
- app/views/primary_source_sets/american-indian-movement/9-15-8279d3bf.md
Waiting on all the AIM transcripts to be corrected, then this will be ready to go!
> AIM Primary Source Set

- app/views/override/legal/tou.md
You can be under 18 to access the site, you just can't donate to the site under age 18.
> Updating TOU per legal

- .github/workflows/CD.yml
- Dockerfile
- aapb
Adds CD action to build docker images automatically on push/pull to `master` branch.
Uses common [WGBH-MLA/.github/.github/workflows/build.yml](https://github.com/WGBH-MLA/.github/blob/main/.github/workflows/build.yml)
> 🏗 Build and publish docker image

- app/views/forms/feedback.html.erb
Fixes link to feedback form
Old form appears to have broken when Tim / Casey left. Recreated new form in MLA shared drive.
> 📝 Feedback form

- app/views/exhibits/black-power.md
updating Ashley Young's affiliation
> Black power exhibit updates

- app/views/exhibits/civil-rights/organizations.md
- app/views/exhibits/civil-rights/people.md
- app/views/exhibits/civil-rights/places.md
Adding new media provided by Alan, then touching up the additions to remove any mistakes
> Nick civil rights edits

- app/assets/stylesheets/globals/override.css.scss
- app/controllers/forms_controller.rb
- app/views/forms/volunteer.html.erb
- app/views/override/donate.md
- app/views/shared/_header_navbar.html.erb
- config/routes.rb
Removed the volunteer.erb form, updated donate form to link to fundraise up page
closes #2829
> Donate volunteer updates

- app/views/exhibits/interviews-with-foreign-leaders/2-people.md
- app/views/exhibits/interviews-with-foreign-leaders/3-country.md
- app/views/exhibits/interviews-with-foreign-leaders/4-date.md
changing the Helmut Schmidt URLs so that it points to the version of the file with audio
> Interviewwithforeignleaders update

- app/views/exhibits/hiv-aids-and-public-broadcasting.md
- app/views/exhibits/stories-of-the-land.md
Alan asked for minor changes to the acknowledgements for SOTL and the HIV/AIDS exhibit.
> Acknowledgment edits

- .github/workflows/aapb-ci.yml
- .github/workflows/specs.yml
- public/data/orgs.json
- public/data/orgs.schema.json
Adds CI job to validate `orgs.json`
- Creates json schema for orgs
- Validates with [schema-validator-action](https://github.com/cardinalby/schema-validator-action)
> adds validation check on orgs.json

- .github/dependabot.yml
> 🦾 Dependabot
