WGBH-MLA/AAPB2

app/views/shared/_footer.html.erb

I had forgotten to update the relative urls for "search" and "resources" when we moved them out of the help directory.

fixes references

---

app/assets/stylesheets/application.css

In production, they cause 404s. In dev, CSS rules are probably being specified twice.

This should never have gotten in

---

app/views/override/help/using-the-ams.md
spec/support/.gitignore
spec/support/link_checker.rb
spec/support/validation_helper.rb
spec/support/validation_helper_spec.rb

I'd want to expand it, but even this found some dead links. The logic for when it's run is a little confusing:
- never on travis (environment variable)
- by default, once a week for developers. (But you can force more frequently by deleting the watch file.)
Particularly if we're hitting remote sites, it can slow down the test suite substantially... but if it's something you have to remember to turn on, then it's not going to happen. This seems like a good balance.
Just scanning for local links right now, and already found a couple bad ones, so I think it's worth it.

Link validation

---

scripts/lib/downloader.rb
spec/scripts/downloader_spec.rb
spec/support/link_checker.rb
spec/support/validation_helper.rb

This should be the end of the work for now. This would catch both 404s and too-many-redirects. The instances below are all examples of the latter.
```
$ rm ./spec/support/.link-check.txt
$ rspec --tag ~not_on_travis # Won't scan links if .link-check.txt is in place.
....
$ grep FAIL ./spec/support/.link-check.txt
FAIL: http://blog.americanarchive.org/2014/03/18/pbcore-is-back-in-action/
FAIL: http://www.current.org/wp-content/themes/current/archive-site/cpb/cpb1202archive.html
FAIL: http://ams.americanarchive.org
FAIL: http://www.archivematica.org
FAIL: http://blog.americanarchive.org
```

Link checker

---

config/vocab-maps/asset-type-map.yml
spec/fixtures/pbcore/clean-bad-relation-and-language.xml

Requires reingest. Empty string in an element required by schema feels little weird, but is easier that customizing facet UI.

Remove "uncataloged" asset type. Fix #407.

---

config/organizations.yml

@sroosa: remember that you need a blank line in between to get paragraphs.
Also, line wrapping will make diffs easier to read.

org config fixes

---

jetty/solr/blacklight-core/conf/solrconfig.xml
spec/features/catalog_spec.rb

It does move the title which includes the search term up the list.
TODO: Is 100x right? Could it be over-weighted? Gather real examples.
Fixes #465.

Make titles 100x more important in text search.

---

app/views/catalog/_search_form_big.html.erb

- Making it an "a" would require more CSS tweaks, but maybe that would be better?
- Does not preserve entered search: if there are any search terms, then we don't get the advanced page. Is that ok? We could set up an actual, separate page at "/advanced", but I'm not sure that's warranted.
- Same thing for smaller search at top?
This PR can be handled independently of a PR for the search page itself.
For reference:

Link to advanced search

---

scripts/lib/cleaner.rb
spec/fixtures/pbcore/clean-basic.xml
spec/fixtures/pbcore/dirty-yes-fix-basic.xml

@caseyedavis12 / @sroosa : Have we seen this problem in any field beyond title, description, and instantiation identifier? Not a problem to make it broader... but it shouldn't be applied to every single element: ie, it's not a problem if multiple instantiationDurations have the same value.

Remove duplicate values. Fix #482

---

app/assets/stylesheets/application.css

Follow up to #550. I actually don't think we want to get rid of the chart entirely: It's the feedback about what facets values are available, just like the counts are for other facets.... But I would like to get the color scheme to match, but the instructions aren't working for me right now. Maybe revisit, if anyone cares.
This PR just gets the slider to look more like our site:

Style slider

---

app/views/override/about-the-american-archive/history/page3.md
spec/fixtures/pbcore/clean-MOCK.xml
spec/models/pb_core_spec.rb

The page3 link is the only one that matters, and removing the dot fixes it.

Warnings raised by link checker

---

app/models/pb_core.rb
app/views/catalog/_index_list_default.html.erb
config/vocab-maps/title-type-map.yml
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-MOCK.xml
spec/fixtures/pbcore/clean-bad-essence-track.xml
spec/fixtures/pbcore/clean-basic.xml
spec/fixtures/pbcore/clean-empty-coverage-type.xml
spec/fixtures/pbcore/clean-empty-description.xml
spec/fixtures/pbcore/clean-no-identifier-source.xml
spec/fixtures/pbcore/clean-no-instantiation-identifier-location-mediaType.xml
spec/fixtures/pbcore/clean-no-instantiation-identifier-source.xml
spec/models/pb_core_spec.rb

Fixes #508.
(Some misgivings about this, but it might be good enough. If we stick with this approach, there will be some follow-up to clean-up: #569.)

Make the official title a semicolon delimited list.

---

app/models/pb_core.rb
spec/models/pb_core_spec.rb

(All the components are still indexed.)
#570 and #568 clash: In one we decided no longer to put the full title on the results page, in the other we started using the "title" method for the full title, instead of just the first portion. When combined, these cause the test failure.
@afred : If you could prioritize this: we have test failures on master right now. Thanks!

Fix #594: No longer index or look for full title string. 

---

scripts/lib/cleaner.rb
spec/fixtures/pbcore/dirty-yes-fix-basic.xml

(If there were none left, existing code fills in "unknown".) Fix #605.

Remove empty title elements and test. 

---

scripts/lib/cleaner.rb
spec/fixtures/pbcore/dirty-no-fix-duplicate-description-removed-error.txt
spec/fixtures/pbcore/dirty-no-fix-duplicate-description-removed.xml
spec/fixtures/pbcore/dirty-no-fix-multi-aai-id-error.txt
spec/fixtures/pbcore/dirty-no-fix-skeleton-error.txt
spec/scripts/cleaner_spec.rb

This still errors on these records, but the error message is much more clear.
Going to say that this fixes #604
```
perl -pne 's/.+\///;s/,.+//' ~/xml-bad.txt | \
xargs ruby scripts/download_clean_ingest.rb \
--same-mount --stdout-log --skip-sitemap --ids
```
All the ones that were bad fall in this category.
@sroosa : I know I talked with you and proposed just loosening the check. Right now, I'm pretty confident this is what we want for the long term... but if we temporarily want a different behavior just to get the records ingested, let's start a new track for that.

Description removed because duplicate 604

---

app/views/catalog/_player.erb

@caseyedavis12 : Is this ok, or should ingest fail if we have ci id, and "other" media type, as we do here? http://americanarchive.org/catalog/cpb-aacip_27-gx44q7r549.pbcore:
```xml
<pbcoreIdentifier source="Sony Ci">ad23e7dbefd346c49fa37de4c26f1515</pbcoreIdentifier>
...
<instantiationMediaType>other</instantiationMediaType>
```
I'm comfortable with this: downside:
- Facet info wrong; icon missing
upside:
- save a lot of recataloging work
Fix #697. @afred : please review.

If media type is "other", just use the audio player

---

app/models/pb_core.rb
lib/formatter.rb
scripts/lib/cleaner.rb
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-MOCK.xml
spec/models/pb_core_spec.rb

Fix #699.
@afred: Please review. This got more complicated than I was thinking at first, but I think it's the right direction. The center of the complexity is `to_solr`: This is only called at index time, so I think it's the right place to ping s3 so that we can tell (1) whether the captions even exist, and (2) what the content is, but only for the purpose of indexing.
I think this will be of increasing utility as we have transcript-y things which don't belong in the pbcore, but which should be indexed for retrieval.

Caption 699

---

app/views/catalog/_organization_facet.erb

Fix #702: The number of numbers was just overwhelming, and the tag-ex logic may have confused the user. This is simpler, though we are sharing less information than we were.

No org counts

---

app/assets/stylesheets/application.css
app/assets/stylesheets/homepage.css
app/views/home/_browse_list.erb
app/views/home/_browse_list_group.erb

@afred: please review.
- Three column layout when narrow, instead of just relying on wrapping, which caused gaps as it got narrower.
- Same styling at all widths.

Mobile homepage browse

---

app/models/pb_core.rb
scripts/lib/cleaner.rb
spec/fixtures/pbcore/dirty-yes-fix-bad-essence-track.xml
spec/fixtures/pbcore/dirty-yes-fix-bad-language.xml

Fix #798. @afred?
Thought about moving the `.tr('/_', '_/')` out of PBCore. If we were starting from scratch I would put everything in Cleaner, but at this point it would mean changing each of the clean fixtures, and it would make all of the live data is slightly out of date... 
If we do it this way, instead, I think the right way to think about it is that there is the real AACIP ID which has a slash, or ought to, and the cleaner fixes it up that way, and there is a distinct AAPB ID for website use which has an underscore instead. Seem ok?

Records from Mississippi should be given clean IDs now.

---

scripts/download_clean_ingest.rb
scripts/lib/downloader.rb
spec/scripts/downloader_spec.rb

@afred: Kevin got an ID list containing an xA0, non-breaking space. That same file works now with this PR. Also moved the cleaning deeper, so it works for either --ids or --id-files.

More robust against weird chars in id list

---

spec/scripts/downloader_spec.rb

@afred? It wouldn't be the end of the world to completely remove the `not_on_travis`, but that's not my preference. Fix #814.

Run downloader tests on Travis. (But not all of them.) Fix #814.

---

app/controllers/catalog_controller.rb
config/environment.rb

yay(?) monkey-patching. @afred? I'm not super confident about our diagnosis of the underlying problem, or of this UI hack to fix it, but it's not unreasonable either. I'm pretty confident that this is not something BL gives us out of the box, judging by the docs.
```
```
Fix #816.

Collapse orgs facet, even when selected.

---

solr_conf/schema.xml
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-sorting.xml
spec/fixtures/pbcore/dirty-yes-fix-sorting.xml

@afred? Towards #818: Individual records will need to be reindexed before they sort correctly, but no new solr fields are created, so this doesn't require a reindex-all.

Sorting again

---

scripts/lib/cleaner.rb
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-bad-title-type.xml
spec/fixtures/pbcore/dirty-yes-fix-bad-title-type.xml
spec/scripts/cleaner_spec.rb

@afred? Did not go with my initial intuition after all: We want to keep the model clean, and ad hoc cleaning heuristics like this should not clutter the model.

In the cleaning phase, transpose articles. Fix #819.

---

Gemfile
Gemfile.lock
app/assets/javascripts/affix.js
app/assets/javascripts/application.js

* Adds jquery-turbolinks gem, which, resolves issues with jquery events not
firing due to turbolinks black magic.
* Requires changing the event to which Affix plugin is applied.
* Closes #611.

Fix broken affixed navigation.

---

app/models/pb_core.rb
scripts/lib/cleaner.rb
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-bad-essence-track.xml
spec/fixtures/pbcore/clean-bad-language.xml
spec/fixtures/pbcore/clean-bad-media-type.xml
spec/fixtures/pbcore/clean-bad-relation-and-language.xml
spec/fixtures/pbcore/clean-bad-title-type-substring.xml
spec/fixtures/pbcore/clean-bad-title-type.xml
spec/fixtures/pbcore/clean-basic.xml
spec/fixtures/pbcore/clean-coverage-type-lc.xml
spec/fixtures/pbcore/clean-empty-coverage-type.xml
spec/fixtures/pbcore/clean-empty-description.xml
spec/fixtures/pbcore/clean-every-title-is-episode-number.xml
spec/fixtures/pbcore/clean-exhibit.xml
spec/fixtures/pbcore/clean-has-rights-already.xml
spec/fixtures/pbcore/clean-no-contributor.xml
spec/fixtures/pbcore/clean-no-creator.xml
spec/fixtures/pbcore/clean-no-identifier-source.xml
spec/fixtures/pbcore/clean-no-instantiation-identifier-location-mediaType.xml
spec/fixtures/pbcore/clean-no-instantiation-identifier-source.xml
spec/fixtures/pbcore/clean-no-instantiation.xml
spec/fixtures/pbcore/clean-no-publisher.xml
spec/fixtures/pbcore/clean-no-relation-type.xml
spec/fixtures/pbcore/clean-rename-attribute.xml
spec/fixtures/pbcore/clean-sorting.xml
spec/fixtures/pbcore/dirty-yes-fix-bad-language.xml

Puts it back into PBCore model, instead of Cleaner.
Needed to fix ID chaos.
Closes #868

Reverts ID conversion

---

app/views/override/contact-us.md

@afred: Fix regression from 9c010c5a7cf. Github rendering is subtly different from the redcarpet renderer we're using... It might be possible to use the github renderer? Filed https://github.com/WGBH/cmless/issues/12. Fix #873

Fix line break regression.

---

app/controllers/media_controller.rb
app/models/user.rb
spec/features/catalog_spec.rb
spec/features/media_spec.rb
spec/models/user_spec.rb

Fixes a bug in media controller.
Refactors spec for tesing media url redirection.
Adds a test for media url redirection given referer of popuparchive.com.
Causes User#aapb_referer? to return false in case of missing or malformed referer value.

Fixes specs for media urls

---

app/views/catalog/show.html.erb

No particular confidence that this format is correct. Right now, I don't think we want to a adopt a button-to-fold-down idiom: The scroll bar does a perfectly good job of hiding information unless you want to see it. Fix #688. @foo4thought ?

Citations. 

---

config/vocab-maps/title-type-map.yml

Moved where "Label" fell on the vocab mapping, so that when the titles are concatenated in the search results display, Label comes towards the end, rather than at the beginning of the title string.

moved label lower

---

app/views/catalog/_player.html.erb

but still no display of transcript.
Maybe VTT instead of SRT would fix that? Fix #1005. @foo4thought ?

Chrome transcript error goes away

---

app/views/catalog/_player.html.erb

Changes value of `crossorigin` property from "anonymous" to "with-credentials",
which allows the caption file to be served from S3, and also sends the cookie
containing the session ID so that the MediaController can successfully retrieve
the user's session, which has the correct value for indicating the user has
agreed to the TOS, which allows the video to play.

Fixes CORS issue with video tracks

---

app/views/catalog/_index_header_default.html.erb

@afred, in checking to see if we already addressed issue 1076 (audio player display issue) and pulling master, I realized that I needed a .present? on the params[:q] conditional in the view.

Adds .present? to conditional in _index.header_default.html.erb

---

scripts/download_clean_ingest.rb
scripts/lib/downloader.rb
spec/scripts/downloader_spec.rb
spec/support/link-check-ignore.txt
spec/support/link_checker.rb

@afred: I did a pretty significant refactor of download.rb, so please give that a thorough review. Also updated test to look for 2 folders before and after ingest. One weird thing I encountered was a link (https://www.statearchivists.org) that failed during the test run in Travis, but not locally, and it looked like an SSL error on Travis. The site itself, if you view the source, shows that it is serving up mixed content. Tried to troubleshoot, but could not get a solid solution, so I added to existing linkchecker ignore file.

1035: Cleans Out Downloads dir after Ingest

---

app/models/caption_file.rb

* Wouldn't find "Mary" for upcased "MARY"
* Closes #1146 
@afred - Not caught in tests with limited fixtures. Another thing to think about refactoring someday?

Upcases caption for capturing index for term in Caption

---

app/views/catalog/_index_header_default.html.erb

@afred - Closes #1083. Issue was a request to hide the thumbnails from screenreaders on the search results page.

1083: Hides thumbnails on search results page for screenreaders

---

app/views/advanced/index.html.erb

@afred: From NCAM's recommendation doc:
"On the Advanced Search page, form field names are labeled with the label element but lack matching id attributes on the inputs fields."
And from W3C:
"The for attribute of the label must exactly match the id of the form control."
* Closes #1088

1088: Adds id to form input

---

app/views/override/about-the-american-archive/funding.md

@afred - Ready for review. This page was pointing to old server for the logos (mlamedia01.wgbh.org) instead of S3.

1236: Funder Logos

---

app/views/override/about-the-american-archive/funding.md

This is done by removing newlines between images and the beginning of
paragraphs. The result is that the image itself is not wrapped in it's
own <p> element, but is containing the the same <p> element as the text,
where existing CSS padding rules apply more cleanly.
Closes #1190.

Moves imgs on Funding static page

---

app/models/user.rb
app/views/catalog/_rules_of_use_modal.html.erb

* Needs to check cookie instead of session
* Also removes unnecessary newlines from the "rules of use" modal.
Fixes #1249

Adjust check for affirmed TOS

---

app/views/catalog/_player.html.erb

@afred - this will make sure we're using latest css inside turbolinks session. solved the issue for me locally.

1267: Marks player css with data-turbolinks-track

---

app/assets/stylesheets/globals/header.css.scss
config/initializers/assets.rb

@afred - @sroosa had me release the latest code to demo (54.211.129.30). In manual testing I found a couple things that need tweaks. First, somehow the sticky nav on the homepage was overflowing on the x axis. Second, the new player.js file wasn't available for transcripts after release. I think precompiling it from assets.rb initializer should fix the issue. 
Could you take a quick look and merge? Thanks!

20170626 release fixes

---

app/assets/javascripts/player.js
app/views/catalog/_player.html.erb

@afred - 2 more things I had to update.
* Need to use javascript_include_tag instead of relative path for JS stub
* Also updates player.js to run on window.load since player wasn't ready on document.ready after update above.

Forgot to use javascript-include_tag for player.js

---

.travis.yml
Gemfile
Gemfile.lock

The latest Ruby version is actually 2.4.1, but jumping that far will require
some dependency resolution, which I found by trying to go just to Ruby 2.3.x.
The reason we're going to 2.2.4 now is because we're changing how we install
ruby on production machines. Instead of installing from source, or using RVM,
we're simply installing the yum package 'ruby22', which brings in the latest
point release, in this case 2.2.4.
This is easier (and faster)from a provisioning standpoint, which is why we're
doing it. But it means that the yum package may move forward with a point
release, and get out of sync with the ruby version specified in the Gemfile.
The result would be that running 'bundle install' will fail, which is something
we should catch when deploying to demo instances (prior to deploying …

Upgrades to ruby 2.2.4

---

app/views/exhibits/newsmagazines.md

Parts of link titles weren't appearing because they weren't formatted correctly in the md.

Update newsmagazine links

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/locals/player.css.scss
app/models/chapter_file.rb
app/views/catalog/_player.html.erb
spec/features/api_spec.rb
spec/features/catalog_spec.rb
spec/fixtures/chapters/cpb-aacip-114-90dv49m9.vtt
spec/fixtures/pbcore/clean-has-chapters.xml
spec/models/chapter_file_spec.rb
spec/scripts/pb_core_ingester_spec.rb
spec/support/fixture-ignore.txt

@afred - This is ready for review. It checks for a chapter file on s3 and displays the chapter button in the VideoJS player if one exists. One thing I don't like here is that I kept getting false HTML validation errors on the new fixture, so I included an option to bypass it (line 447 in catalog_spec). Essentially it kept returning that the video element doesn't have a closing tag, but it does and I could see it in the HTML returned. If you have thoughts on a better implementation for this ticket, they would be much appreciated!

1116 Chapter Files

---

app/views/organizations/md/NCSG55087.md
app/views/organizations/usa.svg

adds basic page for The Library of Congress to the list and map of Participating Organizations. When the Library sends more extensive information and a logo file, we can update the markdown.

1319 add library of congress

---

app/assets/stylesheets/locals/media-tablet.css.scss

@afred - 
* There was Small pixel region where text overlapped
* Reduces font size from 14 to 12 for that region
* Closes #1289

1289: Fixes overlap in "no transcript" text

---

app/assets/stylesheets/globals/exhibits.css.scss
app/views/catalog/_search_header.html.erb
app/views/catalog/index.html.erb
app/views/exhibits/_show_all_items_header.html.erb
spec/aws/s3_spec.rb
spec/features/catalog_spec.rb

Removes Exhibit summary from the top of the Search Results index and replaces with Exhibits breadcrumbs. Also fixes test that was broken by renaming thumbnail (properly) on S3.

1410 exhibit summary

---

app/views/exhibits/show.html.erb
app/views/special_collections/_collection_search.html.erb

Noticed the spinner for search results loading wasn't getting triggered off from links on Exhibits and Special Collections due to turbolinks. This fixes that.

Search Results Spinner from Exhibits and Special Collections

---

app/models/ability.rb
app/models/user.rb
spec/models/abilities/pbcore/can_access_media_url_spec.rb
spec/models/user_spec.rb
spec/support/link-check-ignore.txt

@afred - Could you take a look at this PR? It closes #1149 for turning off referrer checks for assets that have an annotation "Level of User Access ="Online Reading Room" for the domain meptest.dartmouth.edu. I think this should do trick, but if you could take a closer look at the user.rb updates to confirm it would be much appreciated since this is hard to manually test.
In addition, I've reached out to the Dartmouth contact about a manual test from their end where I get them access to my local machine using the ngrok service I've used in the past.

ORR Whitelist for meptest.dartmouth.edu

---

app/views/special_collections/naeb.md

I'm ready to merge this PR @caseyedavis12. But one more question before I do.
I noticed that there was a "special thank you" listed in the optional Funders section that read: Special thanks to Stephanie Sapienza for her contributions to the curation of this collection.
The Funders section was designed to be a logo with some text, so this wasn't rendering at all on the Collection. I moved it to the bottom of the Collection Summary collection. Is that cool? If yes, then I'll get this thing merged. Thanks!

Creates NAEB Special Collection

---

app/models/pb_core.rb
spec/models/pb_core_spec.rb

This will allow the api_controller to show all transcripts of any status per requirement laid out in #1458.
* Closes #1458

Removes transcript_ready? check in place for api_controller

---

app/controllers/catalog_controller.rb
app/models/organization.rb
app/models/pb_core.rb
app/models/to_mods.rb
app/views/catalog/_index_header_default.html.erb
app/views/catalog/_organizations_facet.html.erb
app/views/catalog/show.html.erb
app/views/exhibits/watergate/notes.md
app/views/organizations/show.html.erb
lib/pbcore-2.1.xsd
solr_conf/schema.xml
spec/features/api_spec.rb
spec/features/catalog_spec.rb
spec/features/organizations_spec.rb
spec/fixtures/pbcore/clean-MOCK.mods
spec/fixtures/pbcore/clean-multiple-orgs.xml
spec/models/pb_core_spec.rb
spec/scripts/pb_core_ingester_spec.rb
spec/support/link-check-ignore.txt

@afred - This PR allows for multiple organizations and states to be associated with a record. As a result of this update, we are now using a new XML validation file, updating the view, and had to tweak how we're generating mods xml to conform with the new PBCore standards.

1471 Multiple Organizations + States

---

app/models/organization.rb
app/models/pb_core.rb
app/views/catalog/_index_header_default.html.erb
app/views/catalog/show.html.erb
spec/features/api_spec.rb
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-no-instantiation-location.xml
spec/models/organization_spec.rb
spec/models/pb_core_spec.rb
spec/scripts/pb_core_ingester_spec.rb

@afred @sroosa - Since (per conversation on the ticket) we had to have something exported as an organization from the AMS in the PBCore xml, I implemented this as follows. We look at
`xpaths('/*/pbcoreAnnotation[@annotationType="organization"]')`
and then look for a matching organization. If none are found we don't display any organization information about the record.
This PR also has a small tweak in a separate commit for #1471. Originally it just used the first associated org for the citation. Now it uses all.
Closes #1470.

1470 No Contributor

---

app/models/pb_core.rb
app/views/catalog/show.html.erb
spec/features/catalog_spec.rb
spec/models/pb_core_spec.rb

@afred - this PR limits the IDs shown in the catalog#show view to just AAPB or NOLA ID codes. In particular take a look at the change in catalog_spec.rb please. This was the easiest/fastest way I could think to get around the issue of using our to_solr method to test our views. But I definitely think that is something we should change.
* Closes #1421

Limits IDs in view to AAPB and NOLA

---

app/views/exhibits/_sidebar_nav.html.erb
app/views/exhibits/show.html.erb

Section titles weren't displaying in Exhibits and, while I didn't track down the cause, I think that might have happened when we updated how we were displaying the About pages since they were using a shared template. Broke out the Exhibits in to their own sidebar template so that the section titles would display.

Adds exhibits/_sidebar_nav

---

app/models/pb_core.rb
spec/features/api_spec.rb
spec/features/catalog_spec.rb
spec/fixtures/pbcore/clean-alternative-title.xml
spec/fixtures/pbcore/clean-multiple-episode-numbers-one-series.xml
spec/fixtures/pbcore/clean-multiple-series-with-episode-titles.xml
spec/models/pb_core_spec.rb
spec/scripts/pb_core_ingester_spec.rb

Per the ticket, this PR should apply the title logic expressed below:
"If a record has more than 1 series title, however many episode numbers, and at least one episode title - only use episode titles
If a record has an alternative title, and other titles - don't include the alternative title
If the record has multiple episode numbers, only 1 series title, and however many episode titles - only use the series title and episode title(s)
After these exceptions, keep the logic the same as it currently is."

Completes new title logic

---

app/views/catalog/show.html.erb
spec/features/catalog_spec.rb
spec/support/link-check-ignore.txt

Update show.html.erb to hint at LRA

Update show.html.erb to hint at LRA

---

app/assets/javascripts/player.js

In order to force the video to display paused at the point included in the "#at_[number]_s" playback to a specific timecode we would play the video to get past the poster image and then pause the video at the timecode. Browser autoplay policies changed which broke our JS when it tried to play and then immediately pause. 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
This PR removes that from the JS and, per a short conversation with @sroosa, we're just going to let the poster image display.
Closes #1518

Removes Play and Pause

---

app/controllers/advanced_controller.rb
app/controllers/catalog_controller.rb
app/models/caption_file.rb
app/views/advanced/index.html.erb
app/views/catalog/_constraints.html.erb
app/views/catalog/_search_form_big.html.erb
solr_conf/schema.xml
spec/controllers/advanced_controller_spec.rb
spec/features/advanced_search_spec.rb
spec/rails_helper.rb

-Altered schema to add unstemmed fieldtype, with copyfields to fill in '_unstemmed' versions of all relevant (text content) fields
-When exact match field has input, requires an exact match in one of the new unstemmed field
-The other advanced search fields should work correctly alongside the exact match search.
This should require a reingest to get those farm-fresh _unstemmed fields populated.

1157 no stems

---

app/assets/javascripts/application.js
app/assets/javascripts/player.js
app/views/catalog/_player.html.erb
app/views/layouts/blacklight.html.erb

stub from app js
so individual js files dont get included in applciation.js
include js files in assets rb
so individual js files do get precompiled as separate file_present
javascript_include_tag (not script tag -> override_controller)
dont need turbolinks-track-false (because of meta tag v)
meta reload tag
prevents initial player.js screwup
env.rb
assets.compile = false
dont live compile assets.. for Performance!

Turbolynx Redux

---

app/models/special_collection.rb
app/views/catalog/_player.html.erb
app/views/special_collections/_search_results.html.erb

Closes #1739 and closes #1732. Fixes one of the SpecialCollections searches that broke when we moved to allowing records to be associated with multiple SpecialCollections. Also rescues in catalog#show when a record that is associated with a SpecialCollection but doesn't have CMLess view.

1739 SpecialCollections Fixes

---

app/views/special_collections/newshour.md

Removes a resource link that has nothing to do with this collection and must have been leftover from using another collection as a template when creating this collection.

Update NewsHour resources

---

app/models/organization.rb
app/models/pb_core_presenter.rb
app/views/catalog/_contributing_organizations_facet.html.erb
app/views/organizations/show.html.erb
scripts/lib/cleaner.rb
spec/models/organization_spec.rb

We have organizations that use ampersands (&) in their names and this caused issues during ingest of the xml as well as in display on the front end due to using the name in URLs. This PR should make both of those things do-able for those organizations.

1849 Processes Ampersands in PBCore and Displays on Front End

---

app/models/canonical_url.rb
app/models/pb_core_presenter.rb
app/views/catalog/show.html.erb
config/canonical_urls/url_map.yml
spec/models/canonical_url_spec.rb

We have a small number of records where we'd like to add a canonical url to the head of the record's view. We decided to record these records in a YAML file and add to the view if there's a canonical url present.

Adds CanonicalUrls

---

app/models/canonical_url.rb
app/models/validated_pb_core.rb
lib/rails_stub.rb

This is necessary because new code was causing the ingest to crash when it tried to access `Rails.cache`
Defines the guts of the cache method in `rails_stub`
*Wow!*

Stub Rails.cache method correctly for each method that uses it 

---

app/views/shared/_header_navbar.html.erb

Fixes conditionally showing the navigation search box if there is or is not a special_collection on catalog#index.

1694 Conditionally hides nav search on special_collection searches

---

app/views/catalog/accordion/_supplemental_materials.html.erb
app/views/catalog/show.html.erb

Closes #1950 by moving the Supplemental Materials section in to an accordion on catalog#show.

Moves Supplemental Materials

---

app/models/ability.rb
app/views/embed/show.html.erb
scripts/lib/pb_core_ingester.rb
spec/features/embed_spec.rb
spec/fixtures/pbcore/clean-moving-image-private.xml
spec/fixtures/pbcore/clean-moving-image-protected.xml
spec/fixtures/pbcore/clean-moving-image-public.xml

* Creates a new ability :play_embedded, which mimicks the :play ability, without
the TOS checks.
* Adds logic to check :play_embed ability in the embed view.
* Adds specs for the embed feature for public, protected, and private records.
* Adds new fixtures (actually copies of existing fixtures) with the 3 different
access levels.
* Enhances PdBCore.load_fixtures to accept a list of fixtures you want to load.
Still defaults to all fixtures prefixed with clean-, but now you can be more
selective.
Fixes #1989.

Adds access level checks for embed URLs

---

app/models/pb_core_presenter.rb

Changes `PBCorePresenter#duration` to
-be able to return a duration value
-prefer the "Proxy" machine-generated duration value

Get Correct Duration Value From Machine-Generated 'Proxy' Instantiation

---

app/views/shared/_header_navbar.html.erb

This was a broken link to a Feedback form that we're not implementing through this PR.

Removes Feedback Link from Navigation Dropdown

---

app/models/pb_core_presenter.rb
app/views/catalog/show.html.erb
spec/models/pb_core_spec.rb

New GUID normalization logic was taking whatever guid was in the xml and using that as `id` inside solr. Because of expectations elsewhere in AAPB that '/' guids have been transformed into '_' guids:
-the '/' guid was used on ingest
-MediaController later expected the guid to be a '_'
This is fixed by subbing the '/' to a '_' on ingest. Confirmed that production AAPB solr does not have any '/' guids in it.

Preserve Substitution of / for _ on ingest for consistency with old id logic

---

app/controllers/catalog_controller.rb
app/helpers/snippet_helper.rb
app/models/pb_core_presenter.rb
app/views/catalog/_index_header_default.html.erb

We have text only transcripts from Newshour that were lost in catalog#index when we started to link to timecodes in media based on search params found in the time-coded transcripts. This adds support for transcripts with no timecodes.

1994 Transcripts No Timecode

---

app/models/search_builder.rb
spec/features/catalog_spec.rb

Problem comes in SearchBuilder#apply_quote_handler where parsing of double quoted search phrases
was not getting re-added to the query after being modified to search unstemmed fields.
The process of mutating Solr's 'q' param non-idempotently is inherently problematic, and
attempts to do so for all possible cases in an idempotent way will take some more thinking.

Fixes canned topical searches from homepage

---

app/models/search_builder.rb
spec/features/catalog_spec.rb

There was an error in how the OR operands were getting recombined.
Also adds tests for quoted searches at beginning, at the end, and in the middle
of the original search query URL param.

Fixes quoted phrase searches, again

---

Gemfile
Gemfile.lock

This PBCore gem release completes all the models (except for pbcorePart) and provides factories with Faker data for all PBCore elements, including pbcoreDescriptionDocument, pbcoreInstantiationDocument, and pbcoreInstantiation, which are all "complete" (i.e. all possible attributes have value, and contains either a value or complete instances of children, whichever is applicable).

Updates PBCore gem to 0.2.0

---

app/models/xml_backed.rb

Rights statement was coming back empty from the PBCorePresenter. When cdata is in the REXML node, if there's a newline before the cdata the REXL text method returns the empty string before the cdata. This checks for cdata and returns it if present.

Cdata Newline Fix

---

app/models/organization.rb
app/views/catalog/show.html.erb

Wrong method was used for printing out short name for contributing organizations, needed to explicitly gsub `&amp;` into `&` (as in `Organization#short_name`)

Fix &amp; displaying in citations 

---

app/controllers/captions_controller.rb

Without the BlacklightGUIDFetcher AAPB was returning a 404 when the media player hit captions#show.
Closes #2023

Adds BlackGUIDFetcher for Proper Captions Routing

---

app/assets/stylesheets/globals/bootstrap-killer.css.scss

Something must have changed in how Chrome was rendering because a scroll bar began to appear on the facet panels. The CSS property overflow on the div was being set to auto. Setting to hidden for the facet panel fixed the issue. Closes #2191

Hide overflow for facet panel

---

scripts/lib/downloader.rb
scripts/the_pbcore_corrector.rb

This PR includes 2 things. First, it makes the file runnable as a script with a file path argument. That file should be a list of GUIDs. Second in testing further I found that the download method from the Downloader fails if it cannot find a specific GUID for reindexing. This PR adds a check for results before for assigning the file content, skips the ID if content if the content isn't there, and logs that it is skipping the ID.

ThePBCoreCorrector Update

---

app/views/organizations/md/1708.md

This changes the name, adds a logo, and updates the text for the Arkansas Public Television org page. Because of the name change, this PR should not be released until we're ready to reindex all of the org's records.
Closes #2169

Updates Arkansas Public Television Org Page

---

app/assets/stylesheets/globals/normalize.css.scss
app/helpers/blacklight/facets_helper_behavior.rb
spec/features/catalog_spec.rb

Replaces radio buttons for facets with checkboxes. Radio buttons stopped working in Firefox because they're not valid in this case. Closes #2189

2189 Radio Buttons

---

app/assets/stylesheets/locals/media-mobile.css.scss

For special collections on mobile, the titles are getting chopped off.
The real fix is to be able to nicely display full title regardless of length,
however there are some practical limitation to that. Shrinking the font size
works for many of the titles as a quick fix.

Decreases font size for gallery header

---

app/views/override/about-the-american-archive/whats-new.md

Wraps images in a span that acts like a div, to contain the image and text together. Need
to use span because that's what markdown allows (only inline elements). Then change it's
display to inline-block. Hehe. What a hack. Anything better is welcome.

Fixes image display in Whats New page

---

app/views/embed/show.html.erb
spec/features/embed_spec.rb

When users embedded our player on other sites and our links didn't have the right target attribute, browsers would block content and display a security issue. This adds the attribute so that they open in a new window and don't cause the security issue.

Links back to AAPB from Embed Open in New Window

---

app/views/catalog/show.html.erb

CGI::escape for PBCore titles in catalog#show is converting spaces in the titles to "+" which is causing issues when our newsletter system converts those "+" to "%2B" as that gets literally interpreted by SOLR as part of the title. URI:escape converts the space in a title to "%20" which works.
Tests pass locally except for these 2 which never do.

Uses URI::escape instead of CGI::escape for links to titles

---

app/models/exhibit.rb
app/views/exhibits/conservatism/notes.md

Updates the regex for how we index Exhibit subpages to a specific record. We had an issue where https links were not getting indexed. Also, in running tests, I found that the Conservatism exhibit notes page was broken by the introduction of the config. The new config would load but break when it tried to generate the thumbnail_url for the OG meta tags on the page. Removing extraneous sections from the notes.md fixed the issue.
These two failed 
tests are my local ones that never pass:

Exhibit Link Index Fix

---

app/views/exhibits/peabody/entry-category.md
app/views/exhibits/peabody/winners.md

Changes h3 to h4 on entry category and winners page so that the headers are not the same color as the hyperlinked text.

Peabody headings

---

app/assets/stylesheets/globals/exhibits.css.scss
app/views/exhibits/peabody.md

Adds a class to float an exhibit table right + tweaks location of NHPRC logo on the Peabody exhibit. Approved by Casey.

Change Location of Logo on Peabody

---

public/robots.txt

We want to allow crawling of record pages, but not search results pages.
Also removes config for singling out specific bots, as those rules are intended
to apply to bots that misbehave, but misbehaving bots don't always follow robots.txt.
Instead, we handle misbehaving bots (by agent identifier) in our web server config.

Updates robots.txt

---

scripts/download_clean_ingest.rb

Loads the Rails environment in download_clean_ingest.rb instead of stubbing the Rails module.
The use of ExternalFile within the ingest context was brittle because for some
reason thed download_clean_ingest.rb is explicitly avoiding loading the Rails
environment, and instead methods on the Rails module, such as .cache, and
simply calling Rails.cache.delete in the ExternalFile class caused the ingest
script to fail.
Not sure why the Rails environment was deliberately avoided during the ingest script, other
than a way to save on memory. But it's weird, and leads to brittle code, as this case
highlights.

Fixes error when transcript file is missing (cont)

---

app/views/home/show.html.erb

- Links go to page, not homepage fragment
- `#special-collections` => `special_collections`
- `#exhibits` => `/exhibits`
- Changed menu order
- Special Collections
- Exhibits
- Organizations
- ...
Closes #2127

Update Homepage menu

---

app/views/special_collections/show.html.erb

Fixes #2319
Special Collections with long `Summary` blocks creates a large whitespace on the left side of the page.
Example: https://americanarchive.org/special_collections/radio-kdna
This moves the `Other Resources` box to the left column, below the thumbnail and search box.
- On mobile, `Other Resources` will appear before the summary
- There is a `Funders` block, which was above `Other Resources`
- Should this be moved as well?
- Large `Summary` blocks still have large whitespace, but now slightly less
- Should we move blocks below the `Summary` on the right column?
- Collection Background
- Featured Items

Move "Other Resources" below collection search to reduce whitespace

---

app/assets/stylesheets/globals/exhibits.css.scss

- Fixes aspect ratio of iframe videos with `.exhibit-small-iframe`
- `aspect-ratio: 16 / 9;`
- All podcast videos now show entire thumbnail
- no cropping text or images
- Mobile first:
- Default `width: 100%`
- Large screens
- `min-width: 992px`
- `max-width: 80%`
- `margin-left: 10%`
Closes #2436, closes #2432

iframe proportions

---

solr_conf/schema.xml

In the unstemmed text fields, we had a setting set that would split a word based on a case change in the middle word. "MacDonald" would get split in to "mac" and "donald." Without the split, now we should get "macdonald" as expected. Closes #2285 
Attaching a screenshot for tests. These 2 always fail for me locally.

Removes splitting on case change in unstemmed SOLR text fields

---

app/views/home/show.html.erb

This should replace the picture of Phyllis Schlafly when americanarchive.org is shown as a link preview in outlook, facebook, and other websites.

2464 change homepage og image to aapb logo

---

app/views/catalog/show.html.erb
spec/lib/geo_i_p_country_spec.rb

`URI::encode()` is deprecated: https://ruby-doc.org/stdlib-2.4.4/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description
Replace with suppored `encode_www_form_component` function.
https://ruby-doc.org/stdlib-2.4.4/libdoc/uri/rdoc/URI.html#method-c-encode_www_form_component
Closes #2321

Remove deprecated URI::encode

---

app/controllers/catalog_controller.rb
app/controllers/snippets_controller.rb
app/helpers/application_helper.rb
app/views/catalog/index.html.erb
lib/query_to_terms_array.rb
spec/helpers/snippet_helper_spec.rb
spec/lib/query_to_terms_array_spec.rb

Refactors `ApplicationHelper::query_to_terms_array` to `lib/query_to_terms_array.rb`
Better handles quoted searches and edge cases.
- Splits into sub-functions:
- `terms_array`
- The final array of search terms
- `stopwords`
- Get stopwords from `stopwords.txt`
- Store in Rails cache
- `quoted_phrases`
- Returns list of phrases between two quotation marks as `Array<String>`
- `quoted_terms_arrays`
- Returns terms_array of quoted phrases as `Array<Array<String>>`
- `unquoted_query`
- Returns `String` of original query, minus quoted phrases
- `unquoted_terms`
- Returns `Array<Array<String>>` of all unquoted terms from query, minus stopwords
- `strip_special_chars`
- Removes all non-alphanumeric characters
- Better documentation of steps
- Only parse quotes if even number of `"`
- Queries …

Refactor search query with quotes

---

Dockerfile
aapb

- Better docker command substrings for reusability
- Print `$HELP` if command is not recognized
- Runs rspec tests on file
- With no args, runs full test suite
- Runs `rubocop --autocomplete` on files
- With no args, runs on all files

`./aapb test` and `format` commands

---

app/helpers/snippet_helper.rb
spec/helpers/snippet_helper_spec.rb

Change `"Watch..."` to `"Access..."` because not all content is video. 
Also, the controller can't distinguish between the two without creating a new `PBCorePresenter` for each search result.
Closes #2452

Change all "Watch from here" to "Access from here"

---

app/views/home/_blog.html.erb

Adds an `AAPB Podcast` button inline with the `AAPB on Twitter` and `AAPB on Facebook` buttons.
Closes #2324

Add podcast link under "From the blog"

---

app/views/catalog/show.html.erb

On a record, when clicking on a search link from a title field, the link now includes `&f[access_types][]=all` to show all records, not just the search default of `online`.
Closes MLAAAPB-60

Record title search link: show all results

---

config/routes.rb

... even though the former is a better link name, imo. #shrug.

Redirects /educator_resources to /primary_source_sets

---

app/helpers/blacklight_guid_fetcher.rb
spec/scripts/download_clean_ingest_spec.rb
spec/scripts/downloader_spec.rb

Comment out specs that depend on AMS being up.
This makes the test suite passing again! ✅ 
- `it 'downloads by id'`
- Added `not_on_ci: true`
- Comment out tests that depend on ams being up
- Can't `xit` because `it`'s in a loop
```ruby
patterns.each do |pattern|
it "matches /#{pattern.source}/" do
expect(output).to match pattern
end
end
```
- Some of the tests run on local files, so they can stay
> I really don't think it's a good idea to make the tests dependent on the activity of the catalogers, though this is a good test otherwise.
> ~ Chuck, 2015

✖️ Remove AMS dependant specs

---

app/controllers/logs_controller.rb
config/routes.rb
spec/controllers/logs_controller_spec.rb
spec/scripts/cleaner_spec.rb

* Adds route `/logs` for seeing a list of links to available logs.
* Adds route `/logs/[:log_file_name]` for viewing plain text rendering of an available log file.
* To restrict access to some logs, add the filename (or a glob pattern) to  `LogsController::IGNORE`. Attempting to access an ignored log file will respond with a `403 Forbidden`.

Adds endpoints for viewing some logs.

---

app/controllers/logs_controller.rb
public/robots.txt

* Adds glob patterns to ignore Rails logs that have been rolled.
* Add /logs to robots.txt to prevent search engine indexing.

Ignores more logs and prevents log crawling by bots

---

app/controllers/api_controller.rb

'cache pbcore xsl for json api, re-escape double quotes in xml before json transformation'

Handle json-breaking double quotes in pbcore values in JSON API

---

config/environments/production.rb
scripts/lib/apache_log_parser.rb

```ruby
ruby scripts/lib/apache_log_parser.rb glob/path/to/access_logs
```
* Running this script will not chante Apache config or restart Apache; you must do that deliberately.
* Running this script will only output the worst offenders in terms of number of requests within the log.
* The apache config it outputs can be cut and pasted by a privileged user into the apache config. After apache is restarted, the new config will take effect.
* This will only work using Apache's 'combined' log format. Any changes to the format will probably either break the script outright, or cause it to output invalid data and invalid Apache config. If apache log format changes, assume this script is broke.
* The ApacheLogParser object may be used within a Rails console to further analyze apache logs in …

Adds script to parse apache logs looking for bad bots

---

.gitignore
Dockerfile
Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/iiif_manifest.rb
app/models/pb_core_instantiation.rb
app/models/pb_core_presenter.rb
config/application.rb
config/environments/production.rb
config/initializers/mime_types.rb
lib/iiif_3_0.json
scripts/lib/pb_core_ingester.rb
spec/controllers/catalog_controller_spec.rb

To use, add '.iiif' to a catalog URL to get the IIIF presentation manifest.
Also:
* Updates Dockerfile to multi-stage build for 'development' and 'production'.
* Move RedirectMiddleware to production environment only.
* Use relative path for log location instaed of hard coded path.
* Removes erroneously committed sprockets manifest.
* Updates gitignore to include .vscode.
Closes [#2752](https://github.com/WGBH-MLA/AAPB2/issues/2752).

Iiif endpoint

---

app/controllers/api_controller.rb
app/controllers/catalog_controller.rb

Replaces:
- `cpb-aacip-`
- `cpb-aacip/`
- `cpb-aacip_`
with: `cpb-aacip?`
so that all ID styles can be returned when querying on ID.
Closes #2773
Closes #2827

📟 API endpoint search for old-style IDs

---

.github/workflows/rubocop.yml
.github/workflows/specs.yml

Pins the runner image to `ubuntu-22.04`
`ubuntu-latest` began failing due to missing `sqlite3.h` header. `ubuntu-22.04` builds `sqlite3` successfully, as before.

📌 Pin CI runners to ubuntu 22.04

---

app/controllers/catalog_controller.rb
config/application.rb
spec/cors/cors_spec.rb

Adds Access-Control-Allow-Origin as an exposed response header to Rack::CORS config.
Also,
* Requires dependencies explicitly in CORS spec to allow running in alone.

Add CORS headers explicitly for IIIF requests

---

scripts/lib/apache_log_parser.rb

The BadBotConfigLine class spits out sample apache configuration based to block certain IP address blocks based on their frequency in the apache log. The regex in the script was erroneously matching octet pairs to any part of the clients IP to flag it as a bad bot. This PR fixes the regex to only match the beginning
Fixes #2899

Fixes regex to match beginnig of IP address

---

app/models/pb_core_presenter.rb
spec/models/pb_core_spec.rb

Allows guids to be pushed to AAPB even though they lack a sony ci ID and have the LUA = "Private". This lets us provide metadata only access to Sesame Street content.

allows guids with no sony ci ID but with Private LUA
